// Carrier-LaCAM planner (design.md section 5, milestone M1).
//
// High-level: LaCAM-style DFS over physical configurations with lazy
// operator-level constraint trees (5.2).  Successors are generated by
// Carrier-PIBT (5.4) with greedy rho matching of free robots to serve/clear
// requests (5.3).  The dd_carrier validator is the final arbiter for every
// generated joint operator vector (G1).
#include "../include/dd_planner.hpp"
#include "../include/tapf_assignment.hpp"

#include <algorithm>
#include <chrono>
#include <climits>
#include <cstdlib>

namespace {
long g_guidance_builds = 0;
long g_path_recomputes = 0;
long g_path_cache_hits = 0;

inline int env_int(const char* k, int dflt)
{
  const char* v = std::getenv(k);
  return v ? std::atoi(v) : dflt;
}
}  // namespace
#include <cstring>
#include <deque>
#include <memory>
#include <queue>
#include <random>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace {

using Clock = std::chrono::steady_clock;

// ---------- distance fields ----------
// BFS over walls only; returns dist vector (INT_MAX/2 unreachable)
std::vector<int> bfs_dist(const DDGrid& g, int src)
{
  std::vector<int> d(g.size(), INT_MAX / 2);
  std::deque<int> dq;
  d[src] = 0;
  dq.push_back(src);
  int nb[4];
  while (!dq.empty()) {
    int u = dq.front();
    dq.pop_front();
    const int n = g.neighbors(u, nb);
    for (int k = 0; k < n; ++k)
      if (d[nb[k]] > d[u] + 1) {
        d[nb[k]] = d[u] + 1;
        dq.push_back(nb[k]);
      }
  }
  return d;
}

struct DistCache {
  const DDGrid& g;
  std::unordered_map<int, std::vector<int>> by_src;
  explicit DistCache(const DDGrid& g_) : g(g_) {}
  const std::vector<int>& to(int cell)
  {
    auto it = by_src.find(cell);
    if (it == by_src.end())
      it = by_src.emplace(cell, bfs_dist(g, cell)).first;
    return it->second;
  }
};

// lower-deck distance provider: exact Manhattan on wall-free grids (all
// benchmark suites), BFS cache otherwise.  Kills the dominant per-rollout
// BFS cost without changing any distance value.
struct LowerDist {
  const DDGrid& g;
  bool wallfree;
  DistCache bfs;
  explicit LowerDist(const DDGrid& g_) : g(g_), bfs(g_)
  {
    wallfree = true;
    for (uint8_t w : g.wall) wallfree &= (w == 0);
  }
  int dist(int cell, int from)
  {
    if (wallfree)
      return std::abs(g.row(cell) - g.row(from)) +
             std::abs(g.col(cell) - g.col(from));
    return bfs.to(cell)[from];
  }
};

// ---------- least-blocking path (design 5.3(2)) ----------
// deque-based small-weight Dijkstra: step cost 1 + LAMBDA_BLK * occupied(to).
constexpr int LAMBDA_BLK = 8;

// grid-sized scratch buffers reused across nodes (single-threaded planner)
struct Scratch {
  std::vector<uint8_t> upper;    // upper-deck occupancy flags (per node)
  std::vector<uint8_t> protect;  // protected path/goal cells (per node)
  std::vector<int> grounded;     // 0 none; -1 anon; b+1 grounded target b
  std::vector<int> owner;        // path owner b+1 (per node)
  std::vector<int> dist;         // dijkstra dist / bfs visited
  std::vector<int> prev;         // dijkstra parents
  std::vector<int> upper_base;   // grounded+anon counts for PIBT baseline
  std::vector<uint8_t> upper_path;  // occupancy view for PATH computation:
                                    // targets sitting on their own goals are
                                    // masked free (P1-5 determinism)
  std::vector<uint8_t> on_prev;     // path-inertia scratch (P2-13c)
  const void* occ_node = nullptr;
  const void* pibt_node = nullptr;
  explicit Scratch(int n)
      : upper(n, 0), protect(n, 0), grounded(n, 0), owner(n, 0), dist(n),
        prev(n), upper_base(n, 0), upper_path(n, 0), on_prev(n, 0) {}
};

void fill_occupancy(const DDInstance& ins, const PhysConfig& s, Scratch& sc)
{
  std::fill(sc.upper.begin(), sc.upper.end(), 0);
  std::fill(sc.grounded.begin(), sc.grounded.end(), 0);
  for (int p : s.anon_occ) {
    sc.upper[p] = 1;
    sc.grounded[p] = -1;
  }
  std::vector<bool> carried(ins.n_targets(), false);
  for (int k : s.kappa)
    if (k >= 0) carried[k] = true;
  for (size_t b = 0; b < ins.n_targets(); ++b) {
    sc.upper[s.target_pos[b]] = 1;
    if (!carried[b]) sc.grounded[s.target_pos[b]] = (int)b + 1;
  }
  for (size_t i = 0; i < s.kappa.size(); ++i)
    if (s.kappa[i] == KAPPA_ANON) sc.upper[s.robots[i]] = 1;
  // path view: mask a target's own goal cell ONLY while that target is
  // CARRIED and hovering on the goal — kills the park/deliver circular
  // dependency (debug.md P1-5) at exactly the flip-flop stage, while
  // grounded (completed) targets remain real blockers for path costs.
  sc.upper_path = sc.upper;
  for (size_t i = 0; i < s.kappa.size(); ++i) {
    const int k = s.kappa[i];
    if (k >= 0 && s.target_pos[k] == ins.target_goals[k])
      sc.upper_path[ins.target_goals[k]] = 0;
  }
}

void fill_occupancy_if_needed(const DDInstance& ins, const PhysConfig& s,
                              Scratch& sc, const void* key)
{
  if (sc.occ_node == key && key != nullptr) return;
  fill_occupancy(ins, s, sc);
  sc.occ_node = key;
}

std::vector<int> least_blocking_path(const DDGrid& g, int src, int dst,
                                     const std::vector<uint8_t>& occupied,
                                     int exclude, Scratch& sc,
                                     const std::vector<int>* prev_path = nullptr)
{
  if (src == dst) return {src};
  std::fill(sc.dist.begin(), sc.dist.end(), INT_MAX / 2);
  auto& dist = sc.dist;
  auto& prev = sc.prev;
  prev[src] = -1;
  // path inertia (round-2 P2-13c): scale base costs by 2N and give cells
  // of the PREVIOUS path a -1 discount.  Total discount over any path is
  // < N < 2N = one base unit, so inertia is a strict tie-break — it can
  // never trade away real cost.  Ordering-only (guidance path shape).
  const int scale = 2 * (int)g.size();
  const bool use_prev = prev_path && !prev_path->empty();
  auto& on_prev = sc.on_prev;
  if (use_prev) {
    std::fill(on_prev.begin(), on_prev.end(), 0);
    for (int c : *prev_path) on_prev[c] = 1;
  }
  using QE = std::pair<int, int>;  // (dist, cell)
  std::priority_queue<QE, std::vector<QE>, std::greater<QE>> pq;
  dist[src] = 0;
  pq.push({0, src});
  int nb[4];
  while (!pq.empty()) {
    auto [d, u] = pq.top();
    pq.pop();
    if (d > dist[u]) continue;
    if (u == dst) break;
    const int n = g.neighbors(u, nb);
    for (int k = 0; k < n; ++k) {
      const int v = nb[k];
      const bool occ = v != exclude && occupied[v];
      int w = (1 + (occ ? LAMBDA_BLK : 0)) * scale;
      if (use_prev && on_prev[v]) w -= 1;
      if (dist[v] > d + w) {
        dist[v] = d + w;
        prev[v] = u;
        pq.push({dist[v], v});
      }
    }
  }
  if (dist[dst] >= INT_MAX / 2) return {};
  std::vector<int> path;
  for (int c = dst; c != -1; c = prev[c]) path.push_back(c);
  std::reverse(path.begin(), path.end());
  return path;
}

// per-target cached least-blocking path with lazy invalidation (design 6.2):
// valid while the target position matches and the occupancy status of every
// path cell is unchanged.
struct PathCache {
  // invalidation policy: read once per cache (per solve).  Member rather
  // than function-static so tests can instantiate both policies in one
  // process (debug.md round-2 P0-2).
  bool strict_inval = env_int("DD_STRICT_INVAL", 0) != 0;
  struct Entry {
    std::vector<int> path;
    std::vector<uint8_t> occ_snapshot;  // occupied flag per path cell
    // strict mode only: FULL effective-occupancy snapshot (exclude applied)
    // at compute time.  "any change invalidates" must see OFF-path changes
    // too (audit round-2 P0-2: a detour path is otherwise kept even though
    // the blocked cell it detoured around was vacated) — epoch-free.
    std::vector<uint8_t> full_snapshot;
    int src = -1;
  };
  std::unordered_map<int, Entry> by_target;

  const std::vector<int>& get(const DDGrid& g, int b, int src, int dst,
                              const std::vector<uint8_t>& occupied,
                              int exclude, Scratch& sc)
  {
    auto it = by_target.find(b);
    if (it != by_target.end()) {
      auto& e = it->second;
      // incremental head-advance: the carrier moved one step along the path
      if (e.src != src && e.path.size() >= 2 && e.path[1] == src) {
        e.path.erase(e.path.begin());
        e.occ_snapshot.erase(e.occ_snapshot.begin());
        e.src = src;
        if (!e.occ_snapshot.empty()) e.occ_snapshot[0] = 0;
      }
      if (e.src == src) {
        bool ok = true;
        if (strict_inval) {
          // strict (DD_STRICT_INVAL=1, design 6.2): ANY effective-occupancy
          // change — on or off the cached path — invalidates.  Epoch-free
          // by construction: validity depends only on the CURRENT view.
          for (size_t c = 0; c < occupied.size() && ok; ++c) {
            const bool occ_now = (int)c != exclude && occupied[c];
            ok = occ_now == (e.full_snapshot[c] != 0);
          }
        } else {
          // design 6.2 lazy invalidation (asymmetric): only NEWLY OCCUPIED
          // path cells invalidate; cells that were occupied and became free
          // keep the (conservatively stale, ordering-only) cached path.
          for (size_t i = 0; i < e.path.size() && ok; ++i) {
            const int c = e.path[i];
            const bool occ_now = c != exclude && occupied[c];
            ok = !(occ_now && e.occ_snapshot[i] == 0);
          }
        }
        if (ok) {
          g_path_cache_hits++;
          return e.path;
        }
      }
    }
    Entry e;
    e.src = src;
    g_path_recomputes++;
    const std::vector<int>* prev_path = nullptr;
    if (it != by_target.end() && !it->second.path.empty())
      prev_path = &it->second.path;  // inertia: stale route as tie baseline
    e.path = least_blocking_path(g, src, dst, occupied, exclude, sc,
                                 prev_path);
    e.occ_snapshot.resize(e.path.size());
    for (size_t i = 0; i < e.path.size(); ++i) {
      const int c = e.path[i];
      e.occ_snapshot[i] = (c != exclude && occupied[c]) ? 1 : 0;
    }
    if (strict_inval) {
      e.full_snapshot.resize(occupied.size());
      for (size_t c = 0; c < occupied.size(); ++c)
        e.full_snapshot[c] = ((int)c != exclude && occupied[c]) ? 1 : 0;
    }
    auto res = by_target.insert_or_assign(b, std::move(e));
    return res.first->second.path;
  }
};

// ---------- requests & guidance (design 5.3, M1 greedy) ----------
struct Request {
  enum Kind { SERVE, CLEAR } kind;
  int target = -1;   // for SERVE: target idx; for CLEAR: blocking cell owner
  int cell = -1;     // shelf cell to lift (serve: target pos; clear: blocker)
  int priority = 0;  // higher first (chain head highest)
};

struct Guidance {
  std::vector<Request> requests;
  // rho: robot -> request index (or -1)
  std::vector<int> rho;
  // per-robot goal cell for free robots (request cell)
  std::vector<int> free_goal;
  std::vector<int> parking_cell;  // for ANON carriers: chosen parking cell
  // per-target: next cell along its least-blocking path (guidance for the
  // carrier), -1 if none
  std::vector<int> target_next;
  bool plan_bound = false;  // B1: fixed shelf plan is a HARD constraint
  // per-target: true when the target's goal lies on ANOTHER unfinished
  // target's active path — its carrier must PARK it (clear semantics)
  // instead of delivering into the busy corridor (design 5.4a).  Computed
  // per configuration from the CURRENT masked paths (no parent chain, no
  // registry); deliver/park flip-flop is killed by the carried-hover mask.
  std::vector<uint8_t> target_park;
  std::vector<int> park_owner;  // target idx whose path forced the park
};

struct Node;
using NodePtr = Node*;

// operator constraint (design 5.2): partial assignment robot -> Op
struct Constraint {
  Constraint* parent = nullptr;
  int depth = 0;  // number of robots fixed
  int who = -1;
  Op what;
  std::vector<std::unique_ptr<Constraint>> kids;  // owned by node tree root
};

struct Node {
  PhysConfig X;
  Node* parent = nullptr;
  std::vector<int> order;  // PIBT priority order (may be perturbed, 5.5)
  // IMMUTABLE robot order for constraint-tree expansion (debug.md P0-1,
  // design D11 + 4.2): frozen at node creation so the lazy tree provably
  // enumerates every operator combination exactly once.  Livelock handling
  // must never touch this.
  std::vector<int> constraint_order;
  std::unique_ptr<Constraint> tree_root;
  std::deque<Constraint*> tree_open;  // FIFO within node (LaCAM style)
  Guidance guide;
  int depth = 0;
  // M1 livelock signal (design 5.5): monotone best guidance-h along the
  // parent chain + steps since last improvement
  long h_guidance = 0;
  long best_h = 0;
  int no_progress = 0;
  int revisits = 0;  // duplicate-successor re-pushes (livelock indicator)
  bool macro_tried = false;  // macro successor attempted (design 7.1)
  double g_cost = 0;   // TRUE physical cost from root (design D5)
  double h_adm = 0;    // admissible h_soc (design 5.7)
};

// upper-deck occupancy set of a config (grounded + carried-at-cell)
std::unordered_set<int> upper_cells(const DDInstance& ins, const PhysConfig& s)
{
  std::unordered_set<int> up(s.anon_occ.begin(), s.anon_occ.end());
  for (size_t b = 0; b < ins.n_targets(); ++b) up.insert(s.target_pos[b]);
  for (size_t i = 0; i < s.kappa.size(); ++i)
    if (s.kappa[i] == KAPPA_ANON) up.insert(s.robots[i]);
  return up;
}

// grounded shelf at cell? (target idx >=0, ANON -2, none -1... encode)
struct GroundedIndex {
  std::unordered_map<int, int> target_at;  // cell -> target idx
  std::unordered_set<int> anon_at;
  GroundedIndex(const DDInstance& ins, const PhysConfig& s)
  {
    std::vector<bool> carried(ins.n_targets(), false);
    for (int k : s.kappa)
      if (k >= 0) carried[k] = true;
    for (size_t b = 0; b < ins.n_targets(); ++b)
      if (!carried[b]) target_at[s.target_pos[b]] = (int)b;
    anon_at.insert(s.anon_occ.begin(), s.anon_occ.end());
  }
};

// ---------- guidance construction ----------
constexpr int CLEAR_CHAIN_K = 3;

// ---------- cross-deck wait-for graph (design 5.5, round-2 P2-15) ------
// One out-edge per robot; cycles are structural deadlocks PIBT cannot
// resolve within a step.  Used by the livelock diversification to taboo
// exactly the cycle members' rho pairs (targeted re-match).
static std::vector<int> waitfor_cycles(const DDInstance& ins,
                                       const PhysConfig& s,
                                       const Guidance& g,
                                       LowerDist& lower_dist, Scratch& sc)
{
  const size_t R = ins.n_robots();
  // robot at lower cell
  std::vector<int> robot_at(ins.grid.size(), -1);
  for (size_t i = 0; i < R; ++i) robot_at[s.robots[i]] = (int)i;
  // rho assignee per request cell
  std::vector<int> assignee_of_cell(ins.grid.size(), -1);
  for (size_t i = 0; i < R; ++i)
    if (g.rho[i] >= 0 && g.free_goal[i] >= 0)
      assignee_of_cell[g.free_goal[i]] = (int)i;
  // intended next cell per robot
  auto next_cell = [&](size_t i) -> int {
    const int k = s.kappa[i];
    if (k >= 0 && !g.target_park[k]) return g.target_next[k];
    if (k == KAPPA_ANON || (k >= 0 && g.target_park[k])) {
      const int park = g.parking_cell[i];
      if (park < 0 || park == s.robots[i]) return -1;
      int nb[4];
      const int n = ins.grid.neighbors(s.robots[i], nb);
      int best = -1, bd = INT_MAX / 2;
      for (int t = 0; t < n; ++t) {
        const int d = lower_dist.dist(park, nb[t]);
        if (d < bd) { bd = d; best = nb[t]; }
      }
      return best;
    }
    const int goal = g.free_goal[i];
    if (goal < 0 || goal == s.robots[i]) return -1;
    int nb[4];
    const int n = ins.grid.neighbors(s.robots[i], nb);
    int best = -1, bd = INT_MAX / 2;
    for (int t = 0; t < n; ++t) {
      const int d = lower_dist.dist(goal, nb[t]);
      if (d < bd) { bd = d; best = nb[t]; }
    }
    return best;
  };
  std::vector<int> out(R, -1);
  for (size_t i = 0; i < R; ++i) {
    const int nc = next_cell(i);
    if (nc < 0) continue;
    if (robot_at[nc] >= 0 && robot_at[nc] != (int)i) {
      out[i] = robot_at[nc];  // waits for the robot occupying the cell
      continue;
    }
    // loaded robot waits for a GROUNDED shelf on its next upper cell,
    // which waits for its rho-assigned clearer
    if (s.kappa[i] != KAPPA_FREE && sc.grounded[nc] != 0) {
      const int j = assignee_of_cell[nc];
      if (j >= 0 && j != (int)i) out[i] = j;
    }
  }
  // functional-graph cycle detection
  std::vector<int> color(R, 0);  // 0 white 1 on-stack 2 done
  std::vector<int> in_cycle;
  for (size_t st = 0; st < R; ++st) {
    if (color[st] != 0) continue;
    std::vector<int> stack;
    int cur = (int)st;
    while (cur >= 0 && color[cur] == 0) {
      color[cur] = 1;
      stack.push_back(cur);
      cur = out[cur];
    }
    if (cur >= 0 && color[cur] == 1) {
      // found a cycle: everything from cur onwards in stack
      auto itc = std::find(stack.begin(), stack.end(), cur);
      for (auto p = itc; p != stack.end(); ++p) in_cycle.push_back(*p);
    }
    for (int v : stack) color[v] = 2;
  }
  std::sort(in_cycle.begin(), in_cycle.end());
  return in_cycle;
}



Guidance build_guidance(const DDInstance& ins, const PhysConfig& s,
                        std::vector<DistCache>& target_goal_dist,
                        LowerDist& lower_dist, PathCache& paths, Scratch& sc,
                        const void* node_key, std::vector<int>& park_registry,
                        const std::vector<std::pair<int, int>>* taboo = nullptr,
                        const Guidance* parent_guide = nullptr)
{
  g_guidance_builds++;
  Guidance g;
  const size_t R = ins.n_robots();
  fill_occupancy_if_needed(ins, s, sc, node_key);
  std::fill(sc.protect.begin(), sc.protect.end(), 0);
  std::fill(sc.owner.begin(), sc.owner.end(), 0);
  g.target_next.assign(ins.n_targets(), -1);

  // least-blocking paths (cached) drive serve/clear requests, carrier
  // guidance, and the protected set.
  g.target_park.assign(ins.n_targets(), 0);
  // Active-target cap (throughput, ordering-only): with hundreds of
  // unfinished targets only ACTIVE_CAP get paths/requests/park/protection
  // this node — carried ones first, then nearest-to-goal.  Inactive targets
  // still count in guidance-h; the cap only changes successor ORDERING.
  // adaptive: full guidance below the threshold (r2r-M 230 targets works
  // well uncapped); cap only for very large target counts (dne/s2w 400ish)
  const size_t n_unf_precount = [&]{
    size_t n = 0;
    std::vector<char> cf(ins.n_targets(), 0);
    for (int k : s.kappa) if (k >= 0) cf[k] = 1;
    for (size_t b = 0; b < ins.n_targets(); ++b)
      if (cf[b] || s.target_pos[b] != ins.target_goals[b]) ++n;
    return n;
  }();
  const size_t ACTIVE_CAP =
      n_unf_precount > 256 ? (size_t)env_int("DD_ACTIVE_CAP", 64)
                           : n_unf_precount;
  std::vector<int> active_targets;
  {
    std::vector<char> carried_flag(ins.n_targets(), 0);
    for (int k : s.kappa)
      if (k >= 0) carried_flag[k] = 1;
    std::vector<int> rest;
    for (size_t b = 0; b < ins.n_targets(); ++b) {
      const bool done =
          !carried_flag[b] && s.target_pos[b] == ins.target_goals[b];
      if (done) continue;
      if (carried_flag[b])
        active_targets.push_back((int)b);
      else
        rest.push_back((int)b);
    }
    std::stable_sort(rest.begin(), rest.end(), [&](int a, int b2) {
      const auto& da = target_goal_dist[a].to(ins.target_goals[a]);
      const auto& db = target_goal_dist[b2].to(ins.target_goals[b2]);
      return da[s.target_pos[a]] < db[s.target_pos[b2]];
    });
    for (int b : rest) {
      if (active_targets.size() >= ACTIVE_CAP) break;
      active_targets.push_back(b);
    }
  }
  for (int b_int : active_targets) {
    const size_t b = (size_t)b_int;
    bool carried =
        std::any_of(s.kappa.begin(), s.kappa.end(),
                    [&](int k) { return k == (int)b; });
    const bool done = !carried && s.target_pos[b] == ins.target_goals[b];
    if (done) continue;
    // occupancy for this target's path: every upper cell except itself
    const auto& path = paths.get(ins.grid, (int)b, s.target_pos[b],
                                 ins.target_goals[b], sc.upper_path,
                                 s.target_pos[b], sc);
    if (path.size() >= 2) g.target_next[b] = path[1];
    for (int c : path) {
      sc.protect[c] = 1;
      if (sc.owner[c] == 0) sc.owner[c] = (int)b + 1;
    }

    // design 5.3: serve(b) only when the FIRST path cell is empty on the
    // upper deck; otherwise emit clear requests for the leading blockers.
    const bool head_free = path.size() >= 2 && sc.grounded[path[1]] == 0;
    if (!carried && head_free) {
      Request r;
      r.kind = Request::SERVE;
      r.target = (int)b;
      r.cell = s.target_pos[b];
      r.priority = 100;
      g.requests.push_back(r);
    }
    int emitted = 0;
    for (size_t pi = 1; pi < path.size() && emitted < CLEAR_CHAIN_K; ++pi) {
      const int cur = path[pi];
      const int gr__ = sc.grounded[cur];
      if (gr__ == -1 || (gr__ > 0 && gr__ - 1 != (int)b)) {
        Request r;
        r.kind = Request::CLEAR;
        r.target = (int)b;
        r.cell = cur;
        r.priority = 50 - emitted;  // chain head higher
        g.requests.push_back(r);
        ++emitted;
      }
    }
  }
  // every target goal is protected against parking: a completed target
  // parked back onto a pending goal is the classic serve/clear livelock.
  for (size_t b = 0; b < ins.n_targets(); ++b)
    sc.protect[ins.target_goals[b]] = 1;

  // Park relation (design.md 5.4a).  Semantics:
  //   trigger  — goal_b lies on ANOTHER unfinished target o's active
  //              least-blocking path (detected from the CURRENT X);
  //   release  — as soon as o is complete in the CURRENT X;
  //   cycles   — broken deterministically below (min-index un-parks).
  // Determinism boundary: park is a function of (X, D_b cache epoch) —
  // see tests/test_dd_park_purity.cpp and design.md 5.4a (v2.3).
  g.park_owner.assign(ins.n_targets(), -1);
  auto done_in_X = [&](int o) {
    if (s.target_pos[o] != ins.target_goals[o]) return false;
    for (int k : s.kappa)
      if (k == o) return false;
    return true;
  };
  // PURE function of X (audit P1-5): park[b] iff goal_b lies on another
  // unfinished target's CURRENT masked least-blocking path.  No memory:
  // the carried-hover mask alone kills the deliver/park flip-flop stage,
  // and a search-global registry proved to leak parks across DFS branches
  // (r2r over-parking regression).  park_registry retained in signatures
  // for rollback experiments but neither read nor written here.
  (void)park_registry;
  for (size_t b = 0; b < ins.n_targets(); ++b) {
    const int ow__ = sc.owner[ins.target_goals[b]];
    if (ow__ > 0 && ow__ - 1 != (int)b && !done_in_X(ow__ - 1)) {
      g.target_park[b] = 1;
      g.park_owner[b] = ow__ - 1;
    }
  }
  // carrier head-on deadlock (cross-deck swap, design 5.5): two carried
  // targets whose next path cells are each other's current cells can never
  // pass (R2 forbids the swap; PIBT cannot fix multi-step intent).  Yield
  // rule: the one FARTHER from its goal parks (ties: higher index).
  if (env_int("DD_NO_YIELD", 0) == 0) {
    std::vector<int> carrier_of(ins.n_targets(), -1);
    for (size_t i = 0; i < R; ++i)
      if (s.kappa[i] >= 0) carrier_of[s.kappa[i]] = (int)i;
    for (size_t a = 0; a < ins.n_targets(); ++a) {
      if (carrier_of[a] < 0 || g.target_park[a]) continue;
      const int na = g.target_next[a];
      if (na < 0) continue;
      for (size_t b2 = a + 1; b2 < ins.n_targets(); ++b2) {
        if (carrier_of[b2] < 0 || g.target_park[b2]) continue;
        const int nb2 = g.target_next[b2];
        if (nb2 < 0) continue;
        if (na == s.target_pos[b2] && nb2 == s.target_pos[a]) {
          const auto& da = target_goal_dist[a].to(ins.target_goals[a]);
          const auto& db = target_goal_dist[b2].to(ins.target_goals[b2]);
          const int ra = da[s.target_pos[a]], rb = db[s.target_pos[b2]];
          const size_t yield_b = (ra > rb || (ra == rb)) ? a : b2;
          g.target_park[yield_b] = 1;
          g.park_owner[yield_b] = (int)(yield_b == a ? b2 : a);
        }
      }
    }
  }

  // cycle break: park relations may form cycles (a parks for o, o parks
  // for a, possibly longer).  Walk each cycle and un-park its minimum-index
  // member so exactly one target per cycle delivers first (deterministic).
  for (size_t b = 0; b < ins.n_targets(); ++b) {
    if (!g.target_park[b]) continue;
    // follow owner chain collecting the cycle (bounded by n_targets)
    std::vector<int> chain;
    int cur = (int)b;
    bool cycle = false;
    for (size_t guard = 0; guard <= ins.n_targets(); ++guard) {
      chain.push_back(cur);
      const int nxt = g.target_park[cur] ? g.park_owner[cur] : -1;
      if (nxt < 0) break;
      if (nxt == (int)b) {
        cycle = true;
        break;
      }
      cur = nxt;
    }
    if (cycle) {
      const int drop = *std::min_element(chain.begin(), chain.end());
      g.target_park[drop] = 0;
      g.park_owner[drop] = -1;
    }
  }

  // rho: greedy nearest free robot per request (priority order)
  g.rho.assign(R, -1);
  g.free_goal.assign(R, -1);
  g.parking_cell.assign(R, -1);
  std::vector<int> req_order(g.requests.size());
  for (size_t i = 0; i < req_order.size(); ++i) req_order[i] = (int)i;
  std::stable_sort(req_order.begin(), req_order.end(), [&](int a, int b) {
    return g.requests[a].priority > g.requests[b].priority;
  });
  std::vector<bool> robot_used(R, false);
  int free_left = 0;
  for (size_t i = 0; i < R; ++i) {
    if (s.kappa[i] != KAPPA_FREE)
      robot_used[i] = true;
    else
      ++free_left;
  }
  // eta hysteresis (design 5.3(4), round-2 P2-13b): keeping the parent's
  // (robot, request-cell) pair earns a distance discount, so near-tie
  // re-matches stop flipping every node (reversal jitter).  Ordering-only.
  const int ETA = env_int("DD_ETA", 2);
  const bool use_hyst = parent_guide != nullptr &&
                        parent_guide->free_goal.size() == R && ETA > 0;
  // P2-16a knob: min-cost rho via Hungarian on the top-priority request
  // subset (rows = min(requests, free robots)).  Cost = lower-deck dist
  // minus the same eta hysteresis discount as greedy.  Ordering-only.
  // scale regime (round-2 s2w-timing fix): the O(n^3) matching per node
  // is a clear quality win up to a few hundred targets (r2r 230: mk 614
  // -> 548) but its per-node cost pushes 384..403-target suites past the
  // 10 s first-solution line under parallel contention; greedy was
  // already 25/25 there.  Same 256 boundary as DD_ACTIVE_CAP.
  if (env_int("DD_RHO_HUNGARIAN", 1) != 0 &&
      ins.n_targets() <= (size_t)env_int("DD_RHO_HUNGARIAN_TGT", 256) &&
      free_left > 0 && !req_order.empty()) {
    std::vector<int> free_ids;
    for (size_t i = 0; i < R; ++i)
      if (!robot_used[i]) free_ids.push_back((int)i);
    std::vector<int> rows;
    for (int ri : req_order) {
      if ((int)rows.size() >= (int)free_ids.size()) break;
      rows.push_back(ri);
    }
    std::vector<std::vector<int>> cost(rows.size(),
                                       std::vector<int>(free_ids.size(), 0));
    for (size_t a = 0; a < rows.size(); ++a) {
      const auto& req = g.requests[rows[a]];
      for (size_t b2 = 0; b2 < free_ids.size(); ++b2) {
        const int i = free_ids[b2];
        bool banned = false;
        if (taboo)
          for (auto& [rb, cell] : *taboo)
            banned |= (rb == i && cell == req.cell);
        int dd = banned ? INT_MAX / 8
                        : lower_dist.dist(req.cell, s.robots[i]);
        if (!banned && use_hyst && parent_guide->rho[i] >= 0 &&
            parent_guide->free_goal[i] == req.cell)
          dd -= ETA;
        cost[a][b2] = dd;
      }
    }
    // skeleton reuse (audit 2026-08-30): the ORIGINAL lacam-tapf
    // Hungarian (tapf_assignment), not a copy.
    const auto row_to_col = tapf_hungarian_row_to_col(cost);
    for (size_t a = 0; a < rows.size(); ++a) {
      const int c = row_to_col[a];
      if (c < 0 || cost[a][c] >= INT_MAX / 8) continue;
      const int i = free_ids[c];
      robot_used[i] = true;
      --free_left;
      g.rho[i] = rows[a];
      g.free_goal[i] = g.requests[rows[a]].cell;
    }
  } else
  for (int ri : req_order) {
    if (free_left == 0) break;
    const auto& req = g.requests[ri];
    int best = -1, bestd = INT_MAX / 2;
    for (size_t i = 0; i < R; ++i) {
      if (robot_used[i]) continue;
      if (taboo) {
        bool banned = false;
        for (auto& [rb, cell] : *taboo)
          banned |= (rb == (int)i && cell == req.cell);
        if (banned) continue;
      }
      int dd = lower_dist.dist(req.cell, s.robots[i]);
      if (use_hyst && parent_guide->rho[i] >= 0 &&
          parent_guide->free_goal[i] == req.cell)
        dd -= ETA;
      if (dd < bestd) {
        bestd = dd;
        best = (int)i;
      }
    }
    if (best >= 0) {
      robot_used[best] = true;
      --free_left;
      g.rho[best] = ri;
      g.free_goal[best] = req.cell;
    }
  }

  // parking placement: nearest free cell off every active least-blocking
  // path (protected) with goal-cell fallback.  NOTE: design 5.6 margin/
  // corridor scoring was tried and HURT dense instances (d50 regression);
  // revisit with M2 deadlock machinery.
  std::vector<uint8_t> is_goal_cell(ins.grid.size(), 0);
  for (size_t b = 0; b < ins.n_targets(); ++b)
    is_goal_cell[ins.target_goals[b]] = 1;
  for (size_t i = 0; i < R; ++i) {
    const bool anon_carrier = s.kappa[i] == KAPPA_ANON;
    const bool parked_target_carrier =
        s.kappa[i] >= 0 && g.target_park[s.kappa[i]];
    if (!anon_carrier && !parked_target_carrier) continue;
    int found = -1, fallback = -1;
    // P2-16d knob: escape-degree tie-break among SAME-DEPTH candidates
    // (distance stays primary — the v2.2-rejected scoring traded it away).
    const bool esc_tb = env_int("DD_PLACE_ESCAPE", 0) != 0;
    const int rstart = s.robots[i];
    std::fill(sc.prev.begin(), sc.prev.end(), -1);  // BFS depth marks
    std::deque<int> dq;
    dq.push_back(rstart);
    sc.prev[rstart] = 0;
    int nb[4];
    int found_depth = -1, found_escape = -1;
    while (!dq.empty()) {
      int u = dq.front();
      dq.pop_front();
      const int du = sc.prev[u];
      if (found >= 0 && du > found_depth) break;  // finished the tie layer
      if (u != rstart && !sc.upper[u]) {
        if (!sc.protect[u]) {
          if (!esc_tb) {
            found = u;
            break;
          }
          int escd = 0;
          const int n2 = ins.grid.neighbors(u, nb);
          for (int k = 0; k < n2; ++k)
            if (!sc.upper[nb[k]]) ++escd;
          if (found < 0 || escd > found_escape) {
            found = u;
            found_depth = du;
            found_escape = escd;
          }
        } else if (fallback < 0 && !is_goal_cell[u]) {
          fallback = u;
        }
      }
      const int n = ins.grid.neighbors(u, nb);
      for (int k = 0; k < n; ++k)
        if (sc.prev[nb[k]] < 0) {
          sc.prev[nb[k]] = du + 1;
          dq.push_back(nb[k]);
        }
    }
    g.parking_cell[i] = found >= 0 ? found : fallback;
  }
  return g;
}

// priority order (design 5.4 N.order): loaded-target > loaded-ANON >
// free assigned > free idle; tie-break by remaining distance then id.
std::vector<int> make_order(const DDInstance& ins, const PhysConfig& s,
                            const Guidance& g,
                            std::vector<DistCache>& target_goal_dist)
{
  const size_t R = ins.n_robots();
  std::vector<int> order(R);
  for (size_t i = 0; i < R; ++i) order[i] = (int)i;
  auto cls = [&](int i) {
    if (s.kappa[i] >= 0)
      return g.target_park[s.kappa[i]] ? 1 : 0;  // parked duty ~ clear duty
    if (s.kappa[i] == KAPPA_ANON) return 1;
    if (g.rho[i] >= 0) return 2;
    return 3;
  };
  auto rem = [&](int i) -> int {
    if (s.kappa[i] >= 0) {
      const auto& d = target_goal_dist[s.kappa[i]].to(
          ins.target_goals[s.kappa[i]]);
      return d[s.robots[i]];
    }
    if (g.free_goal[i] >= 0) return 0;  // handled by class
    return 0;
  };
  std::stable_sort(order.begin(), order.end(), [&](int a, int b) {
    const int ca = cls(a), cb = cls(b);
    if (ca != cb) return ca < cb;
    const int ra = rem(a), rb = rem(b);
    if (ra != rb) return ra < rb;
    return a < b;
  });
  return order;
}

// ---------- Carrier-PIBT (design 5.4) ----------
struct PIBTContext {
  const DDInstance& ins;
  const PhysConfig& s;
  const Guidance& g;
  std::vector<DistCache>& target_goal_dist;
  LowerDist& lower_dist;
  std::mt19937& rng;
  // occupancy bookkeeping for the NEXT config being built
  std::vector<Op> ops;              // per robot; kind==WAIT&&to==-2 -> unset
  std::vector<int> next_cell;       // -1 unset
  std::unordered_map<int, int> next_owner;  // next cell -> robot
  std::unordered_map<int, int> upper_cnt;   // DELTAS on top of sc.upper_base
  Scratch& sc;

  void upper_add(int v) { upper_cnt[v]++; }
  void upper_remove(int v)
  {
    auto it = upper_cnt.find(v);
    if (it != upper_cnt.end() && --it->second == 0) upper_cnt.erase(it);
  }
  bool upper_taken(int v) const
  {
    int cnt = sc.upper_base[v];
    auto it = upper_cnt.find(v);
    if (it != upper_cnt.end()) cnt += it->second;
    return cnt > 0;
  }

  PIBTContext(const DDInstance& ins_, const PhysConfig& s_,
              const Guidance& g_, std::vector<DistCache>& tgd,
              LowerDist& ld, std::mt19937& rng_, Scratch& sc_,
              const void* node_key)
      : ins(ins_), s(s_), g(g_), target_goal_dist(tgd), lower_dist(ld),
        rng(rng_), sc(sc_)
  {
    const size_t R = ins.n_robots();
    ops.assign(R, Op{Op::WAIT, -2});
    next_cell.assign(R, -1);
    fill_occupancy_if_needed(ins, s, sc, node_key);
    if (sc.pibt_node != node_key) {
      // per-node baseline: grounded (target+anon) shelves occupy their
      // cells at t+1; carried shelves are registered via deltas on fix.
      std::fill(sc.upper_base.begin(), sc.upper_base.end(), 0);
      for (int p : s.anon_occ) sc.upper_base[p] = 1;
      std::vector<bool> carried__(ins.n_targets(), false);
      for (int k : s.kappa)
        if (k >= 0) carried__[k] = true;
      for (size_t b = 0; b < ins.n_targets(); ++b)
        if (!carried__[b]) sc.upper_base[s.target_pos[b]] = 1;
      sc.pibt_node = node_key;
    }
  }

  bool cell_taken(int v) const { return next_owner.count(v) > 0; }

  bool swap_conflict(int i, int to) const
  {
    // moving i: s.robots[i] -> to; conflict if some j already fixed with
    // next=s.robots[i] and s.robots[j]==to
    auto it = next_owner.find(s.robots[i]);
    if (it == next_owner.end()) return false;
    const int j = it->second;
    return j != i && s.robots[j] == to;
  }

  // candidate ops for robot i in preference order (design 5.4 table)
  std::vector<Op> candidates(int i)
  {
    std::vector<Op> cand;
    const int q = s.robots[i];
    int nb[4];
    const int n = ins.grid.neighbors(q, nb);
    const int k = s.kappa[i];

    auto push_moves_sorted_by = [&](auto&& dist_of, bool loaded) {
      std::vector<int> cells(nb, nb + n);
      std::shuffle(cells.begin(), cells.end(), rng);
      std::stable_sort(cells.begin(), cells.end(),
                       [&](int a, int b) { return dist_of(a) < dist_of(b); });
      for (int v : cells) {
        if (loaded) {
          // S1 pre-filter: destination upper cell free so far
          if (upper_taken(v)) continue;
        }
        cand.push_back(Op::make_move(v));
      }
    };

    if (k >= 0 && !g.target_park[k]) {
      // loaded with target k
      const auto& d = target_goal_dist[k].to(ins.target_goals[k]);
      auto d_of = [&](int c) { return d[c]; };
      if (q == ins.target_goals[k]) {
        cand.push_back(Op::make_drop());
        cand.push_back(Op::make_wait());
        return cand;
      }
      if (g.plan_bound) {
        // B1 hard constraint: only the fixed plan's next cell or waiting
        const int nxt_cell = g.target_next[k];
        if (nxt_cell >= 0 && !upper_taken(nxt_cell)) {
          for (int t2 = 0; t2 < n; ++t2)
            if (nb[t2] == nxt_cell) {
              cand.push_back(Op::make_move(nxt_cell));
              break;
            }
        }
        cand.push_back(Op::make_wait());
        return cand;
      }
      // primary: next cell on the least-blocking path (if legal now)
      const int nxt_cell = g.target_next[k];
      if (nxt_cell >= 0 && !upper_taken(nxt_cell)) {
        for (int t2 = 0; t2 < n; ++t2)
          if (nb[t2] == nxt_cell) {
            cand.push_back(Op::make_move(nxt_cell));
            break;
          }
      }
      push_moves_sorted_by(d_of, /*loaded=*/true);
      // dedupe: drop a duplicate of nxt_cell if present
      if (cand.size() >= 2)
        for (size_t a = 1; a < cand.size(); ++a)
          if (cand[a] == cand[0]) {
            cand.erase(cand.begin() + a);
            break;
          }
      // design 5.4: Drop as a yield when the path head is STRUCTURALLY
      // blocked (grounded shelf), freeing this robot to serve clears.
      const bool structurally_blocked =
          nxt_cell >= 0 && sc.grounded[nxt_cell] != 0;
      if (structurally_blocked) {
        cand.push_back(Op::make_drop());
        cand.push_back(Op::make_wait());
      } else {
        cand.push_back(Op::make_wait());
        cand.push_back(Op::make_drop());  // last resort: yield
      }
    } else if (k == KAPPA_ANON || (k >= 0 && g.target_park[k])) {
      const int park = g.parking_cell[i];
      if (park == q) {
        cand.push_back(Op::make_drop());
        cand.push_back(Op::make_wait());
        return cand;
      }
      if (park >= 0) {
        auto d_of = [&](int c) { return lower_dist.dist(park, c); };
        push_moves_sorted_by(d_of, /*loaded=*/true);
      } else {
        // no parking known: any legal loaded move
        push_moves_sorted_by([](int) { return 0; }, /*loaded=*/true);
      }
      // drop is the last resort (validator-checked); wait before drop
      cand.push_back(Op::make_wait());
      cand.push_back(Op::make_drop());
    } else {
      // free robot
      const int goal = g.free_goal[i];
      if (goal >= 0 && q == goal) {
        // at request cell: lift if grounded shelf present
        if (sc.grounded[q] != 0) cand.push_back(Op::make_lift());
      }
      if (goal >= 0) {
        auto d_of = [&](int c) { return lower_dist.dist(goal, c); };
        push_moves_sorted_by(d_of, /*loaded=*/false);
        cand.push_back(Op::make_wait());
      } else if (sc.protect[q] && env_int("DD_IDLE_AVOID", 1)) {
        // idle ON an active path / requested-shelf / goal cell (design
        // 5.4, round-2 P2-13d): step OFF the corridor first — waiting here
        // means being pushed every step (reversal jitter) and physically
        // blocking lifts.  Prefer un-protected neighbors, then wait, then
        // protected moves (still pushable).
        auto d_of = [&](int c) { return sc.protect[c] ? 1 : 0; };
        push_moves_sorted_by(d_of, /*loaded=*/false);
        // insert Wait before the protected fallback moves
        size_t first_prot = 0;
        while (first_prot < cand.size() &&
               !(cand[first_prot].kind == Op::MOVE &&
                 sc.protect[cand[first_prot].to]))
          ++first_prot;
        cand.insert(cand.begin() + first_prot, Op::make_wait());
      } else {
        // idle off-corridor: prefer to stay put; move only when pushed
        cand.push_back(Op::make_wait());
        push_moves_sorted_by([](int) { return 0; }, /*loaded=*/false);
      }
    }
    return cand;
  }

  // try to fix robot i to op; returns false on conflict with already-fixed
  bool feasible(int i, const Op& op) const
  {
    int to = s.robots[i];
    if (op.kind == Op::MOVE) to = op.to;
    if (cell_taken(to)) return false;
    if (op.kind == Op::MOVE && swap_conflict(i, op.to)) return false;
    if (op.kind == Op::MOVE && s.kappa[i] != KAPPA_FREE) {
      // S1: carried shelf enters `to` at t+1
      if (upper_taken(to)) return false;
    }
    if (op.kind == Op::LIFT) {
      if (sc.grounded[to] == 0) return false;
    }
    if (op.kind == Op::DROP && s.kappa[i] == KAPPA_ANON) {
      // the carried ANON shelf itself is not registered until fixed, so any
      // count at q belongs to ANOTHER shelf -> S1
      if (upper_taken(to)) return false;
    }
    return true;
  }

  // exact upper-deck bookkeeping delta for fixing robot i to op:
  // grounded shelves are pre-registered; a LIFTED shelf stays at its cell
  // (already counted).  A carried shelf occupies `to` at t+1 for
  // WAIT/MOVE/DROP.
  bool carried_occupies(const Op& op, int i) const
  {
    return s.kappa[i] != KAPPA_FREE &&
           (op.kind == Op::WAIT || op.kind == Op::MOVE ||
            op.kind == Op::DROP);
  }

  void fix(int i, const Op& op)
  {
    int to = s.robots[i];
    if (op.kind == Op::MOVE) to = op.to;
    ops[i] = op;
    next_cell[i] = to;
    next_owner[to] = i;
    if (carried_occupies(op, i)) upper_add(to);
  }

  void unfix(int i, const Op& op)
  {
    int to = s.robots[i];
    if (op.kind == Op::MOVE) to = op.to;
    next_owner.erase(to);
    next_cell[i] = -1;
    ops[i] = Op{Op::WAIT, -2};
    if (carried_occupies(op, i)) upper_remove(to);
  }
};

// recursive PIBT: fix robot i (priority index), pushing occupants
bool pibt_fix(PIBTContext& ctx, const std::vector<int>& order, int i,
              const std::vector<Op>* forced, int depth_guard)
{
  if (depth_guard > (int)ctx.ins.n_robots() * 4) return false;
  const int robot = order[i];
  if (ctx.next_cell[robot] != -1) return true;  // already fixed

  std::vector<Op> cand;
  if (forced && !((*forced)[robot] == Op{Op::WAIT, -2})) {
    cand = {(*forced)[robot]};
  } else {
    cand = ctx.candidates(robot);
  }
  for (const Op& op : cand) {
    if (!ctx.feasible(robot, op)) continue;
    // standard PIBT: if MOVE destination currently hosts an UNDECIDED robot,
    // fix us tentatively and immediately recurse on the occupant; backtrack
    // to our next candidate if the occupant cannot be placed.
    int occupant = -1;
    if (op.kind == Op::MOVE) {
      for (size_t j = 0; j < ctx.ins.n_robots(); ++j)
        if ((int)j != robot && ctx.s.robots[j] == op.to &&
            ctx.next_cell[j] == -1) {
          occupant = (int)j;
          break;
        }
    }
    ctx.fix(robot, op);
    if (occupant >= 0) {
      int occ_pos = -1;
      for (size_t k2 = 0; k2 < order.size(); ++k2)
        if (order[k2] == occupant) occ_pos = (int)k2;
      if (occ_pos < 0 ||
          !pibt_fix(ctx, order, occ_pos, forced, depth_guard + 1)) {
        ctx.unfix(robot, op);
        continue;
      }
    }
    return true;
  }
  // last resort: wait (if wait cell not taken by someone else this step)
  Op w = Op::make_wait();
  if (ctx.feasible(robot, w)) {
    ctx.fix(robot, w);
    return true;
  }
  return false;
}

// generate successor configuration honoring constraint chain (nullopt if
// generator failed — allowed under partial constraints, G1)
std::optional<std::pair<PhysConfig, std::vector<Op>>> carrier_pibt(
    const DDInstance& ins, Node& node, Constraint* c,
    std::vector<DistCache>& tgd, LowerDist& ld, std::mt19937& rng,
    Scratch& sc, DDStats* stats)
{
  const size_t R = ins.n_robots();
  // collect forced ops from constraint chain (each depth fixes one robot)
  std::vector<Op> forced(R, Op{Op::WAIT, -2});
  for (Constraint* p = c; p && p->depth > 0; p = p->parent)
    forced[p->who] = p->what;

  // G1 (design 4.2, debug.md P0-2): when the constraint covers ALL robots,
  // the deterministic two-deck validator is the sole arbiter — no PIBT
  // feasibility logic in the way.
  if (c->depth == (int)R) {
    if (stats) stats->pibt_calls++;
    std::vector<Op> ops(forced);
    auto nxt = apply_ops(ins, node.X, ops);
    if (!nxt.has_value()) {
      if (stats) stats->g1_rejects++;  // expected: exhaustive enumeration
      return std::nullopt;
    }
    return std::make_pair(*nxt, ops);
  }

  PIBTContext ctx(ins, node.X, node.guide, tgd, ld, rng, sc, &node);
  if (stats) stats->pibt_calls++;

  // apply forced ops first (in priority order among forced robots)
  for (int r : node.order) {
    if (!(forced[r] == Op{Op::WAIT, -2})) {
      if (!ctx.feasible(r, forced[r])) {
        if (stats) stats->generator_failures++;
        return std::nullopt;
      }
      ctx.fix(r, forced[r]);
    }
  }
  for (size_t i = 0; i < R; ++i) {
    if (!pibt_fix(ctx, node.order, (int)i, &forced, 0)) {
      if (stats) stats->generator_failures++;
      return std::nullopt;
    }
  }
  // normalize unset ops (shouldn't happen) to WAIT
  for (size_t i = 0; i < R; ++i)
    if (ctx.ops[i].kind == Op::WAIT && ctx.ops[i].to == -2)
      ctx.ops[i] = Op::make_wait();

  // FINAL ARBITER (G1): the two-deck validator
  auto nxt = apply_ops(ins, node.X, ctx.ops);
  if (!nxt.has_value()) {
    if (stats) stats->validator_rejects++;
    return std::nullopt;
  }
  return std::make_pair(*nxt, ctx.ops);
}

// enumerate legal local ops of robot r at node (design 5.2 branching)
std::vector<Op> legal_local_ops(const DDInstance& ins, const PhysConfig& s,
                                int r, Scratch& sc, const void* node_key)
{
  fill_occupancy_if_needed(ins, s, sc, node_key);
  std::vector<Op> out;
  const int q = s.robots[r];
  out.push_back(Op::make_wait());
  int nb[4];
  const int n = ins.grid.neighbors(q, nb);
  for (int k = 0; k < n; ++k) out.push_back(Op::make_move(nb[k]));
  if (s.kappa[r] == KAPPA_FREE) {
    if (sc.grounded[q] != 0) out.push_back(Op::make_lift());
  } else {
    out.push_back(Op::make_drop());
  }
  return out;
}

}  // namespace

// ---------- rollout core (design 7.1 / D13; shared by B0 and macro) ----------
// From configuration X, repeatedly apply the UNCONSTRAINED Carrier-PIBT
// generator.  Stops on: goal, any lift/drop event AFTER at least one step
// (event boundary), step cap, generator failure, or revisiting a
// configuration inside this rollout (local cycle).  Returns the trace.
struct RolloutResult {
  std::vector<std::vector<Op>> trace;  // joint ops, possibly empty
  PhysConfig end;                      // final configuration
  double cost = 0;                     // physical cost of the trace (D5)
  bool reached_goal = false;
};

double dd_edge_cost(const PhysConfig& X, const std::vector<Op>& ops);

RolloutResult rollout_from(const DDInstance& ins, const PhysConfig& X0,
                           int max_steps, int min_chunk,
                           std::vector<DistCache>& tgd, LowerDist& ld,
                           PathCache& paths, Scratch& sc,
                           std::vector<int>& park_registry, std::mt19937& rng,
                           DDStats* stats, bool stop_on_event)
{
  RolloutResult out;
  out.end = X0;
  std::unordered_set<uint64_t> local_seen;
  uint64_t roll_hash = phys_config_hash(X0);  // maintained incrementally
  local_seen.insert(roll_hash);
  Node tmp;  // reused across steps; guidance refreshed every GUIDE_EVERY
  const int GUIDE_EVERY = env_int("DD_GUIDE_EVERY", 8);
  for (int step = 0; step < max_steps; ++step) {
    if (is_dd_goal(ins, out.end)) {
      out.reached_goal = true;
      return out;
    }
    tmp.X = out.end;
    if (step % GUIDE_EVERY == 0) {
      // guidance frozen within the chunk (ordering-only staleness);
      // occupancy is refreshed every step below.
      sc.occ_node = nullptr;
      Guidance prev_guide = std::move(tmp.guide);
      tmp.guide = build_guidance(ins, tmp.X, tgd, ld, paths, sc, &tmp,
                                 park_registry, nullptr,
                                 step > 0 ? &prev_guide : nullptr);
      tmp.order = make_order(ins, tmp.X, tmp.guide, tgd);
      tmp.constraint_order = tmp.order;
    }
    Constraint root;
    // tmp/config change every step: invalidate address-keyed scratch state.
    sc.occ_node = nullptr;
    sc.pibt_node = nullptr;
    auto res = carrier_pibt(ins, tmp, &root, tgd, ld, rng, sc, stats);
    if (!res.has_value()) return out;
    auto& [X_new, ops] = *res;
    roll_hash = phys_config_hash_incremental(ins, out.end, ops, roll_hash);
    if (!local_seen.insert(roll_hash).second) return out;
    out.cost += dd_edge_cost(out.end, ops);
    out.trace.push_back(ops);
    out.end = X_new;
    if (stats) stats->macro_steps++;
    if (is_dd_goal(ins, out.end)) {
      out.reached_goal = true;
      return out;
    }
    if (stop_on_event && step >= min_chunk) {
      for (const Op& op : ops)
        if (op.kind == Op::LIFT || op.kind == Op::DROP) return out;
    }
  }
  return out;
}


// physical cost of one joint op from configuration X (design 2.3, weights 1)
// solver-objective weights (round-2 P2-16b): unit by default (design v1);
// DD_SOLVER_WEIGHTS=1 folds DD_ALPHA..DD_DELTA into g / admissible-h /
// rollout cost consistently (f-pruning stays admissible: h only uses
// alpha-scaled loaded distance + gamma-scaled lift/drop lower bounds).
struct SolverWeights {
  double alpha = 1, beta = 1, gamma = 1, delta = 1;
};
static SolverWeights g_weights;  // refreshed at every solve entry
static void refresh_solver_weights()
{
  SolverWeights w;
  if (env_int("DD_SOLVER_WEIGHTS", 0) != 0) {
    if (const char* e = getenv("DD_ALPHA")) w.alpha = atof(e);
    if (const char* e = getenv("DD_BETA")) w.beta = atof(e);
    if (const char* e = getenv("DD_GAMMA")) w.gamma = atof(e);
    if (const char* e = getenv("DD_DELTA")) w.delta = atof(e);
  }
  g_weights = w;
}

double dd_edge_cost(const PhysConfig& X, const std::vector<Op>& ops)
{
  const SolverWeights& w = g_weights;
  double c = 0;
  for (size_t i = 0; i < ops.size(); ++i) {
    if (ops[i].kind == Op::MOVE) {
      c += X.kappa[i] == KAPPA_FREE ? w.beta : w.alpha;
      if (X.kappa[i] == KAPPA_ANON) c += w.delta;
    } else if (ops[i].kind == Op::LIFT || ops[i].kind == Op::DROP) {
      c += w.gamma;
    }
  }
  return c;
}

// admissible h_soc (design 5.7): per unfinished target, wall-only upper
// distance + remaining lift/drop count (2 uncarried / 1 carried).
double dd_admissible_h(const DDInstance& ins, const PhysConfig& X,
                       std::vector<DistCache>& tgd)
{
  const SolverWeights& w = g_weights;
  double h = 0;
  std::vector<char> carried(ins.n_targets(), 0);
  for (int k : X.kappa)
    if (k >= 0) carried[k] = 1;
  for (size_t b = 0; b < ins.n_targets(); ++b) {
    const bool done = !carried[b] && X.target_pos[b] == ins.target_goals[b];
    if (done) continue;
    const auto& d = tgd[b].to(ins.target_goals[b]);
    h += w.alpha * d[X.target_pos[b]];
    h += w.gamma * (carried[b] ? 1 : 2);
  }
  return h;
}

namespace {
struct PhaseOpts {
  bool macro_enabled = true;
  bool stop_at_first = false;      // return as soon as an incumbent exists
  double incumbent_init = -1;      // externally supplied upper bound
};
}  // namespace

static DDPlan dd_solve_phase(const DDInstance& ins,
                             Clock::time_point t_hard_end, int seed,
                             DDStats* stats, DDPlan* best_effort,
                             const PhaseOpts& opt, double* incumbent_out)
{
  const auto t_start = Clock::now();
  auto expired = [&]() { return Clock::now() >= t_hard_end; };
  std::mt19937 rng(seed);
  const size_t R = ins.n_robots();

  // distance caches: per target goal field (upper wall-only) + lower fields
  std::vector<DistCache> target_goal_dist;
  target_goal_dist.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b)
    target_goal_dist.emplace_back(ins.grid);
  LowerDist lower_dist(ins.grid);
  PathCache path_cache;
  Scratch scratch(ins.grid.size());
  std::vector<int> park_registry(ins.n_targets(), -1);

  // node storage
  std::deque<std::unique_ptr<Node>> all_nodes;
  std::unordered_map<PhysConfig, Node*, PhysConfigHasher> explored;
  // parent op edge for solution extraction
  // edge = op sequence (1 step for primitive edges, >1 for macro edges)
  std::unordered_map<Node*, std::pair<Node*, std::vector<std::vector<Op>>>>
      parent_edge;

  // guidance-h: sum over unfinished targets of goal distance (+2 lift/drop
  // proxy).  Ordering-only signal for the livelock detector; the O(B*R)
  // approach term was dropped for throughput.
  auto guidance_h = [&](const PhysConfig& X) -> long {
    long h = 0;
    for (size_t b = 0; b < ins.n_targets(); ++b) {
      bool carried = false;
      for (int k : X.kappa) carried |= (k == (int)b);
      const bool done = !carried && X.target_pos[b] == ins.target_goals[b];
      if (done) continue;
      const auto& d = target_goal_dist[b].to(ins.target_goals[b]);
      h += d[X.target_pos[b]] + 2;
    }
    return h;
  };
  constexpr int LIVELOCK_WINDOW = 24;

  auto make_node = [&](PhysConfig&& X, Node* parent) -> Node* {
    all_nodes.push_back(std::make_unique<Node>());
    Node* nd = all_nodes.back().get();
    nd->X = std::move(X);
    nd->parent = parent;
    nd->depth = parent ? parent->depth + 1 : 0;
    nd->h_guidance = guidance_h(nd->X);
    nd->best_h = parent ? std::min(parent->best_h, nd->h_guidance)
                        : nd->h_guidance;
    nd->no_progress =
        (parent && nd->h_guidance >= parent->best_h) ? parent->no_progress + 1
                                                     : 0;
    // M1 livelock signal (design 5.5): no guidance-h improvement for a
    // window -> shuffle order within classes + taboo the parent's rho pairs
    std::vector<std::pair<int, int>> taboo;
    const bool livelock = nd->no_progress > 0 &&
                          nd->no_progress % LIVELOCK_WINDOW == 0;
    if (livelock && parent) {
      // wait-for refinement (round-2 P2-15): taboo ONLY the rho pairs of
      // robots on wait-for cycles when any exist — targeted re-match
      // beats blanket diversification; blanket taboo is the fallback.
      scratch.occ_node = nullptr;
      fill_occupancy(ins, nd->X, scratch);
      const auto cyc = waitfor_cycles(ins, nd->X, parent->guide, lower_dist,
                                      scratch);
      if (!cyc.empty()) {
        for (int i : cyc)
          if (parent->guide.rho[i] >= 0)
            taboo.emplace_back(i, parent->guide.free_goal[i]);
      }
      if (taboo.empty()) {
        for (size_t i = 0; i < ins.n_robots(); ++i)
          if (parent->guide.rho[i] >= 0)
            taboo.emplace_back((int)i, parent->guide.free_goal[i]);
      }
    }
    nd->guide = build_guidance(ins, nd->X, target_goal_dist, lower_dist,
                               path_cache, scratch, nd, park_registry,
                               livelock ? &taboo : nullptr,
                               (!livelock && parent) ? &parent->guide
                                                     : nullptr);
    nd->order = make_order(ins, nd->X, nd->guide, target_goal_dist);
    nd->constraint_order = nd->order;  // frozen for the node's lifetime
    if (livelock) {
      // shuffle within equal-priority classes only: order was built with
      // stable sort by (class, rem, id); shuffle whole order but re-sort by
      // class keeps classes, randomizes within.
      std::shuffle(nd->order.begin(), nd->order.end(), rng);
      std::stable_sort(nd->order.begin(), nd->order.end(),
                       [&](int a, int b) {
                         auto cls = [&](int i) {
                           if (nd->X.kappa[i] >= 0) return 0;
                           if (nd->X.kappa[i] == KAPPA_ANON) return 1;
                           if (nd->guide.rho[i] >= 0) return 2;
                           return 3;
                         };
                         return cls(a) < cls(b);
                       });
    }
    nd->h_adm = dd_admissible_h(ins, nd->X, target_goal_dist);
    nd->tree_root = std::make_unique<Constraint>();
    nd->tree_open.push_back(nd->tree_root.get());
    if (stats) {
      stats->hl_nodes++;
      if (nd->depth > stats->max_depth) {
        stats->max_depth = nd->depth;
        stats->deepest_config = nd->X;
      }
      long done = 0;
      for (size_t b = 0; b < ins.n_targets(); ++b) {
        bool carried = false;
        for (int k : nd->X.kappa) carried |= (k == (int)b);
        if (!carried && nd->X.target_pos[b] == ins.target_goals[b]) ++done;
      }
      stats->best_targets_done = std::max(stats->best_targets_done, done);
    }
    return nd;
  };

  auto extract_plan = [&](Node* nd) {
    DDPlan plan;
    for (Node* cur = nd; cur && parent_edge.count(cur);) {
      auto& [p, seq] = parent_edge[cur];
      for (auto it = seq.rbegin(); it != seq.rend(); ++it)
        plan.push_back(*it);
      cur = p;
    }
    std::reverse(plan.begin(), plan.end());
    if (plan.empty()) plan.push_back(std::vector<Op>(R, Op::make_wait()));
    return plan;
  };

  Node* root = make_node(initial_phys_config(ins), nullptr);
  explored.emplace(root->X, root);
  if (is_dd_goal(ins, root->X)) return extract_plan(root);

  Node* deepest = root;
  std::vector<Node*> open;  // DFS stack
  open.push_back(root);

  // anytime state (design 5.7; debug.md P3)
  DDPlan best_plan;
  double incumbent = opt.incumbent_init;  // may carry phase-1 upper bound
  bool stop_now = false;
  auto on_goal = [&](Node* nd) {
    const double soc = nd->g_cost;
    if (opt.stop_at_first) stop_now = true;
    if (incumbent < 0 || soc < incumbent - 1e-9) {
      incumbent = soc;
      best_plan = extract_plan(nd);
      if (stats) {
        stats->incumbent_updates++;
        stats->best_soc = incumbent;
        if (stats->first_solution_ms < 0) {
          stats->first_solution_ms =
              std::chrono::duration<double, std::milli>(Clock::now() - t_start)
                  .count();
          stats->first_solution_soc = soc;
        }
      }
    }
  };

  while (!open.empty() && !expired() && !stop_now) {
    if (incumbent >= 0 && !best_plan.empty() &&
        incumbent <= root->h_adm + 1e-9) {
      if (incumbent_out) *incumbent_out = incumbent;
      return best_plan;  // incumbent matches the admissible bound: optimal
    }
    // FOCAL-lite selection after the first solution: among the top of the
    // stack pick the min-f entry (bounded scan, ordering only)
    Node* nd = open.back();
    if (incumbent >= 0) {
      const size_t K = std::min<size_t>(open.size(), 32);
      size_t best_i = open.size() - 1;
      double best_f = 1e18;
      for (size_t j = open.size() - K; j < open.size(); ++j) {
        const double f = open[j]->g_cost + open[j]->h_adm;
        if (f < best_f) {
          best_f = f;
          best_i = j;
        }
      }
      nd = open[best_i];
      open.erase(open.begin() + best_i);
      open.push_back(nd);
    }
    // f-pruning: g + admissible h >= incumbent cannot improve
    if (incumbent >= 0 && nd->g_cost + nd->h_adm >= incumbent - 1e-9) {
      if (stats) stats->f_pruned++;
      open.pop_back();
      continue;
    }
    if (is_dd_goal(ins, nd->X)) {
      on_goal(nd);
      open.pop_back();
      continue;
    }
    if (nd->tree_open.empty()) {
      open.pop_back();
      continue;
    }
    Constraint* c = nd->tree_open.front();
    nd->tree_open.pop_front();
    if (stats) stats->hl_expanded++;

    // macro successor (design 7.1, D13): on the node's FIRST expansion,
    // roll the unconstrained generator to the next lift/drop event (or cap)
    // and insert the terminal configuration as an extra successor tried
    // FIRST.  Constraint tree untouched -> completeness unaffected.
    // two-phase policy (ablation-verified): macro is a FEASIBILITY device;
    // greedy rollout traces pad plan cost at scale, so the anytime
    // improvement phase (incumbent found) runs WITHOUT macro successors.
    const int msparse = env_int("DD_MACRO_SPARSE", 1);
    if (opt.macro_enabled && c->depth == 0 && !nd->macro_tried &&
        incumbent < 0 && (msparse <= 1 || nd->depth % msparse == 0)) {
      nd->macro_tried = true;
      auto reg_copy = park_registry;  // speculative: do not pollute registry
      // design 7.1: on large instances free-travel phases are long, so we
      // force a minimum chunk; on small ones stop at the FIRST event.
      const int min_chunk =
          (int)ins.n_targets() > 64 ? env_int("DD_MACRO_MIN", 15) : 0;
      auto r = rollout_from(ins, nd->X, env_int("DD_MACRO_CAP", 64), min_chunk,
                            target_goal_dist, lower_dist,
                            path_cache, scratch, reg_copy, rng, stats,
                            /*stop_on_event=*/true);
      // scratch keys were invalidated by rollout; nothing stale remains
      if (r.trace.size() >= 2 && !explored.count(r.end)) {
        PhysConfig X_macro = r.end;
        Node* mchild = make_node(std::move(X_macro), nd);
        mchild->g_cost = nd->g_cost + r.cost;
        explored.emplace(mchild->X, mchild);
        parent_edge[mchild] = {nd, r.trace};
        if (stats) {
          stats->macro_successors++;
          if (incumbent >= 0) stats->macro_after_first++;
        }
        if (is_dd_goal(ins, mchild->X)) {
          on_goal(mchild);
        } else {
          nd->tree_open.push_front(c);  // re-queue the popped constraint
          open.push_back(mchild);
          continue;  // try the macro child first (DFS top)
        }
        nd->tree_open.push_front(c);
        continue;
      }
    }

    // low-level lazy expansion (design 5.1)
    if (c->depth < (int)R) {
      const int r = nd->constraint_order[c->depth];
      for (const Op& op : legal_local_ops(ins, nd->X, r, scratch, nd)) {
        c->kids.push_back(std::make_unique<Constraint>());
        Constraint* k = c->kids.back().get();
        k->parent = c;
        k->depth = c->depth + 1;
        k->who = r;
        k->what = op;
        nd->tree_open.push_back(k);
      }
    }
    // keep node on stack while its tree is non-empty
    auto res = carrier_pibt(ins, *nd, c, target_goal_dist, lower_dist, rng,
                            scratch, stats);
    if (!res.has_value()) continue;
    auto& [X_new, ops] = *res;

    auto it = explored.find(X_new);
    if (it != explored.end()) {
      if (stats) stats->duplicate_configs++;
      Node* ex = it->second;
      // LaCAM*-style relax/rewire (design 4.3, round-2 P2-14): a CHEAPER
      // route into an explored configuration updates its g and parent edge
      // and reopens it, so descendants get relaxed transitively through
      // further duplicate hits.  Restores the eventually-better anytime
      // behaviour that first-visit locking forfeited.
      const double g_new = nd->g_cost + dd_edge_cost(nd->X, ops);
      if (g_new < ex->g_cost - 1e-9) {
        ex->g_cost = g_new;
        parent_edge[ex] = {nd, {ops}};
        if (stats) stats->g_relaxed++;
        if (is_dd_goal(ins, ex->X)) {
          on_goal(ex);
        } else if (open.empty() || open.back() != ex) {
          open.push_back(ex);  // reopen with the cheaper prefix
        }
      }
      // LaCAM revisit semantics + M1 livelock signal (design 5.5): on heavy
      // revisiting, re-match rho with the node's current pairs tabooed and
      // reshuffle the intra-class order.  Ordering only — completeness kept.
      ex->revisits++;
      // legal diversification (D11-compliant): allow a FRESH macro rollout
      // on heavy revisiting — rng has advanced, so the probe differs; the
      // constraint tree/variable order stay untouched.
      if (ex->revisits % 8 == 0) ex->macro_tried = false;
      if (ex->revisits % 8 == 0) {
        std::vector<std::pair<int, int>> taboo;
        for (size_t i = 0; i < R; ++i)
          if (ex->guide.rho[i] >= 0)
            taboo.emplace_back((int)i, ex->guide.free_goal[i]);
        ex->guide = build_guidance(ins, ex->X, target_goal_dist, lower_dist,
                                   path_cache, scratch, ex, park_registry,
                                   &taboo);
        ex->order = make_order(ins, ex->X, ex->guide, target_goal_dist);
        std::shuffle(ex->order.begin(), ex->order.end(), rng);
        std::stable_sort(ex->order.begin(), ex->order.end(), [&](int a, int b) {
          auto cls = [&](int i) {
            if (ex->X.kappa[i] >= 0) return 0;
            if (ex->X.kappa[i] == KAPPA_ANON) return 1;
            if (ex->guide.rho[i] >= 0) return 2;
            return 3;
          };
          return cls(a) < cls(b);
        });
      }
      if (!ex->tree_open.empty() && (open.empty() || open.back() != ex))
        open.push_back(ex);
      continue;
    }
    Node* child = make_node(std::move(X_new), nd);
    child->g_cost = nd->g_cost + dd_edge_cost(nd->X, ops);
    explored.emplace(child->X, child);
    parent_edge[child] = {nd, {ops}};
    if (child->depth > deepest->depth) deepest = child;
    if (is_dd_goal(ins, child->X)) {
      on_goal(child);
      continue;
    }
    open.push_back(child);
  }
  if (stats) {
    stats->timed_out = stats->timed_out || best_plan.empty();
    stats->guidance_builds = g_guidance_builds;
    stats->path_recomputes = g_path_recomputes;
    stats->path_cache_hits = g_path_cache_hits;
  }
  if (incumbent_out) *incumbent_out = incumbent;
  if (!best_plan.empty()) return best_plan;
  if (best_effort) *best_effort = extract_plan(deepest);
  return {};
}

DDPlan solve_carrier_lacam(const DDInstance& ins, double time_limit_sec,
                           int seed, DDStats* stats, DDPlan* best_effort)
{
  refresh_solver_weights();
  // Two-phase anytime (ablation-verified):
  //   phase 1: macro rollout ON, stop at the FIRST solution -> fast,
  //            feasibility-oriented upper bound (greedy traces padded);
  //   phase 2: fresh primitive-only search from the root for the remaining
  //            budget, pruned by the phase-1 bound -> quality plan.
  // Returns the better of the two.  DD_MACRO_CAP=0 degenerates to a single
  // primitive-only phase (ablation knob semantics preserved).
  const auto t_end = Clock::now() +
                     std::chrono::duration_cast<Clock::duration>(
                         std::chrono::duration<double>(time_limit_sec));
  PhaseOpts p1;
  // scale-regime rule (same 64-target boundary as ACTIVE_CAP/min_chunk):
  // macro rollout helps dense small/mid instances but pads plan cost when
  // hundreds of targets are involved (full-suite A/B, 2026-08-30).
  p1.macro_enabled = env_int("DD_MACRO_CAP", 64) > 0 &&
                     ins.n_targets() <= (size_t)env_int("DD_MACRO_TGT", 64);
  p1.stop_at_first = true;
  double inc1 = -1;
  DDPlan plan1 =
      dd_solve_phase(ins, t_end, seed, stats, best_effort, p1, &inc1);
  if (Clock::now() >= t_end)
    return plan1;  // no budget left for the quality phase

  PhaseOpts p2;
  p2.macro_enabled = false;
  p2.stop_at_first = false;
  p2.incumbent_init = inc1;  // -1 if phase 1 failed
  double inc2 = -1;
  DDStats st2;
  DDPlan plan2 = dd_solve_phase(ins, t_end, seed + 1, &st2, nullptr, p2,
                                &inc2);
  if (stats) {
    // merge phase-2 stats that matter for reporting
    stats->hl_nodes += st2.hl_nodes;
    stats->hl_expanded += st2.hl_expanded;
    stats->pibt_calls += st2.pibt_calls;
    stats->duplicate_configs += st2.duplicate_configs;
    stats->f_pruned += st2.f_pruned;
    stats->g_relaxed += st2.g_relaxed;
    if (st2.incumbent_updates > 0) {
      stats->incumbent_updates += st2.incumbent_updates;
      stats->best_soc = inc2;
    }
    stats->timed_out = plan1.empty() && plan2.empty();
  }
  if (plan2.empty()) return plan1;
  if (plan1.empty()) return plan2;
  return (inc2 >= 0 && (inc1 < 0 || inc2 < inc1)) ? plan2 : plan1;
}


DDPlan solve_carrier_rollout(const DDInstance& ins, double time_limit_sec,
                             int seed, DDStats* stats)
{
  refresh_solver_weights();
  const auto t_start = Clock::now();
  std::mt19937 rng(seed);
  std::vector<DistCache> tgd;
  tgd.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b) tgd.emplace_back(ins.grid);
  LowerDist ld(ins.grid);
  PathCache paths;
  Scratch sc(ins.grid.size());
  std::vector<int> park_registry(ins.n_targets(), -1);

  DDPlan plan;
  PhysConfig X = initial_phys_config(ins);
  if (is_dd_goal(ins, X)) {
    plan.push_back(std::vector<Op>(ins.n_robots(), Op::make_wait()));
    return plan;
  }
  std::unordered_set<uint64_t> seen;
  seen.insert(phys_config_hash(X));
  while (std::chrono::duration<double>(Clock::now() - t_start).count() <
         time_limit_sec) {
    auto r = rollout_from(ins, X, 512, 0, tgd, ld, paths, sc, park_registry,
                          rng, stats, /*stop_on_event=*/false);
    for (auto& ops : r.trace) plan.push_back(std::move(ops));
    X = r.end;
    if (r.reached_goal) return plan;
    if (r.trace.empty()) {
      if (stats) stats->generator_failures++;
      return {};  // stuck: honest failure (no search to recover)
    }
    if (!seen.insert(phys_config_hash(X)).second) return {};  // global cycle
  }
  if (stats) stats->timed_out = true;
  return {};
}


double dd_root_admissible_h(const DDInstance& ins)
{
  std::vector<DistCache> tgd;
  tgd.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b) tgd.emplace_back(ins.grid);
  return dd_admissible_h(ins, initial_phys_config(ins), tgd);
}

DDPlan solve_carrier_2stage(const DDInstance& ins, double time_limit_sec,
                            int seed, DDStats* stats,
                            std::vector<std::vector<int>>* fixed_paths_out)
{
  refresh_solver_weights();
  const auto t_start = Clock::now();
  std::mt19937 rng(seed);
  std::vector<DistCache> tgd;
  tgd.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b) tgd.emplace_back(ins.grid);
  LowerDist ld(ins.grid);
  Scratch sc(ins.grid.size());

  // ---- stage 1: freeze per-target least-blocking paths at X0 ----
  PhysConfig X = initial_phys_config(ins);
  fill_occupancy(ins, X, sc);
  std::vector<std::vector<int>> fixed(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b) {
    fixed[b] = least_blocking_path(ins.grid, ins.target_starts[b],
                                   ins.target_goals[b], sc.upper,
                                   ins.target_starts[b], sc);
    if (fixed[b].empty()) return {};  // no wall-feasible path
  }
  if (fixed_paths_out) *fixed_paths_out = fixed;
  // static park relation: goal_b on another target's FIXED path
  std::vector<uint8_t> park(ins.n_targets(), 0);
  std::vector<int> park_owner(ins.n_targets(), -1);
  for (size_t b = 0; b < ins.n_targets(); ++b)
    for (size_t o = 0; o < ins.n_targets(); ++o) {
      if (o == b) continue;
      for (int c : fixed[o])
        if (c == ins.target_goals[b]) {
          park[b] = 1;
          park_owner[b] = (int)o;
          break;
        }
      if (park[b]) break;
    }

  // per-target progress index along its fixed path
  std::vector<size_t> idx(ins.n_targets(), 0);

  auto build_2stage_guidance = [&](const PhysConfig& s) {
    Guidance g;
    const size_t R = ins.n_robots();
    fill_occupancy(ins, s, sc);
    std::fill(sc.protect.begin(), sc.protect.end(), 0);
    g.target_next.assign(ins.n_targets(), -1);
    g.target_park.assign(ins.n_targets(), 0);
    g.park_owner.assign(ins.n_targets(), -1);
    auto done_in_X = [&](int o) {
      if (s.target_pos[o] != ins.target_goals[o]) return false;
      for (int k : s.kappa)
        if (k == o) return false;
      return true;
    };
    for (size_t b = 0; b < ins.n_targets(); ++b) {
      // advance the frozen-plan index to the target's current cell if it
      // matches (targets may only move ALONG the plan by construction)
      while (idx[b] + 1 < fixed[b].size() &&
             fixed[b][idx[b]] != s.target_pos[b])
        ++idx[b];
      if (fixed[b][idx[b]] != s.target_pos[b]) idx[b] = 0;  // safety
      const bool carried = [&] {
        for (int k : s.kappa)
          if (k == (int)b) return true;
        return false;
      }();
      const bool done = !carried && s.target_pos[b] == ins.target_goals[b];
      if (done) continue;
      for (size_t j = idx[b]; j < fixed[b].size(); ++j)
        sc.protect[fixed[b][j]] = 1;
      if (idx[b] + 1 < fixed[b].size())
        g.target_next[b] = fixed[b][idx[b] + 1];
      if (park[b] && park_owner[b] >= 0 && !done_in_X(park_owner[b])) {
        g.target_park[b] = 1;
        g.park_owner[b] = park_owner[b];
      }
      // serve/clear off the FIXED plan
      const int nxt = g.target_next[b];
      const bool head_free = nxt >= 0 && sc.grounded[nxt] == 0;
      if (!carried && head_free && !g.target_park[b]) {
        Request r;
        r.kind = Request::SERVE;
        r.target = (int)b;
        r.cell = s.target_pos[b];
        r.priority = 100;
        g.requests.push_back(r);
      }
      int emitted = 0;
      for (size_t j = idx[b] + 1;
           j < fixed[b].size() && emitted < CLEAR_CHAIN_K; ++j) {
        const int cur = fixed[b][j];
        const int gr = sc.grounded[cur];
        if (gr == -1 || (gr > 0 && gr - 1 != (int)b)) {
          Request r;
          r.kind = Request::CLEAR;
          r.target = (int)b;
          r.cell = cur;
          r.priority = 50 - emitted;
          g.requests.push_back(r);
          ++emitted;
        }
      }
    }
    for (size_t b = 0; b < ins.n_targets(); ++b)
      sc.protect[ins.target_goals[b]] = 1;
    // rho greedy (same as main guidance)
    g.rho.assign(R, -1);
    g.free_goal.assign(R, -1);
    g.parking_cell.assign(R, -1);
    std::vector<int> req_order(g.requests.size());
    for (size_t i = 0; i < req_order.size(); ++i) req_order[i] = (int)i;
    std::stable_sort(req_order.begin(), req_order.end(), [&](int a, int b2) {
      return g.requests[a].priority > g.requests[b2].priority;
    });
    std::vector<bool> used(R, false);
    int free_left = 0;
    for (size_t i = 0; i < R; ++i) {
      if (s.kappa[i] != KAPPA_FREE)
        used[i] = true;
      else
        ++free_left;
    }
    for (int ri : req_order) {
      if (free_left == 0) break;
      const auto& req = g.requests[ri];
      int best = -1, bestd = INT_MAX / 2;
      for (size_t i = 0; i < R; ++i) {
        if (used[i]) continue;
        const int dd = ld.dist(req.cell, s.robots[i]);
        if (dd < bestd) {
          bestd = dd;
          best = (int)i;
        }
      }
      if (best >= 0) {
        used[best] = true;
        --free_left;
        g.rho[best] = ri;
        g.free_goal[best] = req.cell;
      }
    }
    // parking for ANON / parked-target carriers: nearest off-protect cell
    for (size_t i = 0; i < R; ++i) {
      const bool anon_c = s.kappa[i] == KAPPA_ANON;
      const bool parked_c = s.kappa[i] >= 0 && g.target_park[s.kappa[i]];
      if (!anon_c && !parked_c) continue;
      int found = -1, fallback = -1;
      std::fill(sc.prev.begin(), sc.prev.end(), 0);
      std::deque<int> dq;
      dq.push_back(s.robots[i]);
      sc.prev[s.robots[i]] = 1;
      int nb[4];
      while (!dq.empty() && found < 0) {
        int u = dq.front();
        dq.pop_front();
        if (u != s.robots[i] && !sc.upper[u]) {
          if (!sc.protect[u]) {
            found = u;
            break;
          }
          if (fallback < 0) {
            bool is_goal = false;
            for (size_t b2 = 0; b2 < ins.n_targets(); ++b2)
              if (ins.target_goals[b2] == u) {
                is_goal = true;
                break;
              }
            if (!is_goal) fallback = u;
          }
        }
        const int n = ins.grid.neighbors(u, nb);
        for (int k = 0; k < n; ++k)
          if (!sc.prev[nb[k]]) {
            sc.prev[nb[k]] = 1;
            dq.push_back(nb[k]);
          }
      }
      g.parking_cell[i] = found >= 0 ? found : fallback;
    }
    return g;
  };

  // ---- stage 2: rolling execution with the fixed-plan guidance ----
  DDPlan plan;
  if (is_dd_goal(ins, X)) {
    plan.push_back(std::vector<Op>(ins.n_robots(), Op::make_wait()));
    return plan;
  }
  std::unordered_set<uint64_t> seen;
  uint64_t hash = phys_config_hash(X);
  seen.insert(hash);
  Node tmp;
  while (std::chrono::duration<double>(Clock::now() - t_start).count() <
         time_limit_sec) {
    tmp.X = X;
    sc.occ_node = nullptr;
    sc.pibt_node = nullptr;
    tmp.guide = build_2stage_guidance(X);
    tmp.guide.plan_bound = true;
    tmp.order = make_order(ins, tmp.X, tmp.guide, tgd);
    tmp.constraint_order = tmp.order;
    Constraint root;
    PathCache dummy_paths;
    auto res = carrier_pibt(ins, tmp, &root, tgd, ld, rng, sc, stats);
    if (!res.has_value()) return {};
    auto& [X_new, ops] = *res;
    hash = phys_config_hash_incremental(ins, X, ops, hash);
    if (!seen.insert(hash).second) return {};  // cycle -> honest failure
    plan.push_back(ops);
    X = X_new;
    if (is_dd_goal(ins, X)) return plan;
  }
  if (stats) stats->timed_out = true;
  return {};
}

std::vector<PhysConfig> dd_enumerate_node_successors(const DDInstance& ins,
                                                     const PhysConfig& X,
                                                     int seed)
{
  std::mt19937 rng(seed);
  std::vector<DistCache> target_goal_dist;
  target_goal_dist.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b)
    target_goal_dist.emplace_back(ins.grid);
  LowerDist lower_dist(ins.grid);
  PathCache path_cache;
  Scratch scratch(ins.grid.size());
  std::vector<int> park_registry(ins.n_targets(), -1);

  Node node;
  node.X = X;
  node.guide = build_guidance(ins, node.X, target_goal_dist, lower_dist,
                              path_cache, scratch, &node, park_registry);
  node.order = make_order(ins, node.X, node.guide, target_goal_dist);
  node.constraint_order = node.order;
  node.tree_root = std::make_unique<Constraint>();
  node.tree_open.push_back(node.tree_root.get());

  std::vector<PhysConfig> out;
  std::unordered_set<uint64_t> seen;
  const size_t R = ins.n_robots();
  while (!node.tree_open.empty()) {
    Constraint* c = node.tree_open.front();
    node.tree_open.pop_front();
    if (c->depth < (int)R) {
      const int r = node.constraint_order[c->depth];
      for (const Op& op : legal_local_ops(ins, node.X, r, scratch, &node)) {
        c->kids.push_back(std::make_unique<Constraint>());
        Constraint* k = c->kids.back().get();
        k->parent = c;
        k->depth = c->depth + 1;
        k->who = r;
        k->what = op;
        node.tree_open.push_back(k);
      }
    }
    auto res = carrier_pibt(ins, node, c, target_goal_dist, lower_dist, rng,
                            scratch, nullptr);
    if (!res.has_value()) continue;
    const auto& X_new = res->first;
    if (seen.insert(phys_config_hash(X_new)).second) out.push_back(X_new);
  }
  return out;
}

std::vector<PhysConfig> dd_enumerate_node_successors_reguided(
    const DDInstance& ins, const PhysConfig& X, int seed, int n_reguides,
    std::vector<int>* constraint_order_before,
    std::vector<int>* constraint_order_after)
{
  std::mt19937 rng(seed);
  std::vector<DistCache> target_goal_dist;
  target_goal_dist.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b)
    target_goal_dist.emplace_back(ins.grid);
  LowerDist lower_dist(ins.grid);
  PathCache path_cache;
  Scratch scratch(ins.grid.size());
  std::vector<int> park_registry(ins.n_targets(), -1);

  Node node;
  node.X = X;
  node.guide = build_guidance(ins, node.X, target_goal_dist, lower_dist,
                              path_cache, scratch, &node, park_registry);
  node.order = make_order(ins, node.X, node.guide, target_goal_dist);
  node.constraint_order = node.order;
  if (constraint_order_before) *constraint_order_before = node.constraint_order;
  node.tree_root = std::make_unique<Constraint>();
  node.tree_open.push_back(node.tree_root.get());

  // production re-guidance mutation (verbatim semantics of the revisit
  // branch in dd_solve_phase): taboo current rho pairs, rebuild guidance,
  // rebuild + shuffle + class-sort the PIBT order.  constraint_order is
  // deliberately NOT touched — that is the invariant under test.
  auto reguide = [&]() {
    std::vector<std::pair<int, int>> taboo;
    for (size_t i = 0; i < ins.n_robots(); ++i)
      if (node.guide.rho[i] >= 0)
        taboo.emplace_back((int)i, node.guide.free_goal[i]);
    scratch.occ_node = nullptr;
    scratch.pibt_node = nullptr;
    node.guide = build_guidance(ins, node.X, target_goal_dist, lower_dist,
                                path_cache, scratch, &node, park_registry,
                                &taboo);
    node.order = make_order(ins, node.X, node.guide, target_goal_dist);
    std::shuffle(node.order.begin(), node.order.end(), rng);
    std::stable_sort(node.order.begin(), node.order.end(),
                     [&](int a, int b) {
                       auto cls = [&](int i) {
                         if (node.X.kappa[i] >= 0) return 0;
                         if (node.X.kappa[i] == KAPPA_ANON) return 1;
                         if (node.guide.rho[i] >= 0) return 2;
                         return 3;
                       };
                       return cls(a) < cls(b);
                     });
  };

  std::vector<PhysConfig> out;
  std::unordered_set<uint64_t> seen;
  const size_t R = ins.n_robots();
  size_t pops = 0;
  int applied = 0;
  while (!node.tree_open.empty()) {
    // interleave: first re-guide mid-drain (partially expanded tree), then
    // every R further pops until n_reguides applications are done.
    if (applied < n_reguides && pops > 0 && pops % (R + 1) == 0) {
      reguide();
      ++applied;
    }
    ++pops;
    Constraint* c = node.tree_open.front();
    node.tree_open.pop_front();
    if (c->depth < (int)R) {
      const int r = node.constraint_order[c->depth];
      for (const Op& op : legal_local_ops(ins, node.X, r, scratch, &node)) {
        c->kids.push_back(std::make_unique<Constraint>());
        Constraint* k = c->kids.back().get();
        k->parent = c;
        k->depth = c->depth + 1;
        k->who = r;
        k->what = op;
        node.tree_open.push_back(k);
      }
    }
    auto res = carrier_pibt(ins, node, c, target_goal_dist, lower_dist, rng,
                            scratch, nullptr);
    if (!res.has_value()) continue;
    const auto& X_new = res->first;
    if (seen.insert(phys_config_hash(X_new)).second) out.push_back(X_new);
  }
  while (applied < n_reguides) {  // ensure requested count even on tiny trees
    reguide();
    ++applied;
  }
  if (constraint_order_after) *constraint_order_after = node.constraint_order;
  return out;
}

std::vector<uint8_t> dd_compute_park(const DDInstance& ins,
                                     const PhysConfig& X,
                                     int warm_block_cell, bool strict_inval,
                                     std::vector<int>* path_out)
{
  std::vector<DistCache> target_goal_dist;
  target_goal_dist.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b)
    target_goal_dist.emplace_back(ins.grid);
  LowerDist lower_dist(ins.grid);
  PathCache path_cache;
  path_cache.strict_inval = strict_inval;
  Scratch scratch(ins.grid.size());
  std::vector<int> park_registry(ins.n_targets(), -1);

  if (warm_block_cell >= 0) {
    // occupied->vacated history: warm each unfinished target's cached path
    // under an occupancy where warm_block_cell is occupied, mirroring the
    // exact production call shape (self-excluded source cell).
    std::vector<uint8_t> occ(ins.grid.size(), 0);
    for (size_t b = 0; b < ins.n_targets(); ++b) occ[X.target_pos[b]] = 1;
    for (int c : X.anon_occ) occ[c] = 1;
    occ[warm_block_cell] = 1;
    for (size_t b = 0; b < ins.n_targets(); ++b) {
      const bool done = X.target_pos[b] == ins.target_goals[b];
      if (done) continue;
      path_cache.get(ins.grid, (int)b, X.target_pos[b], ins.target_goals[b],
                     occ, X.target_pos[b], scratch);
    }
  }

  Node node;
  node.X = X;
  scratch.occ_node = nullptr;
  scratch.pibt_node = nullptr;
  node.guide = build_guidance(ins, node.X, target_goal_dist, lower_dist,
                              path_cache, scratch, &node, park_registry);
  if (path_out) {
    path_out->clear();
    // re-query target 0's path exactly as guidance saw it (cache hit)
    scratch.occ_node = nullptr;
    fill_occupancy(ins, node.X, scratch);
    *path_out = path_cache.get(ins.grid, 0, X.target_pos[0],
                               ins.target_goals[0], scratch.upper_path,
                               X.target_pos[0], scratch);
  }
  return node.guide.target_park;
}

std::vector<int> dd_match_free_goals(const DDInstance& ins,
                                     const PhysConfig& X,
                                     const std::vector<int>* parent_free_goal)
{
  std::vector<DistCache> target_goal_dist;
  target_goal_dist.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b)
    target_goal_dist.emplace_back(ins.grid);
  LowerDist lower_dist(ins.grid);
  PathCache path_cache;
  Scratch scratch(ins.grid.size());
  std::vector<int> park_registry(ins.n_targets(), -1);
  Guidance parent;
  const Guidance* pg = nullptr;
  if (parent_free_goal) {
    parent.free_goal = *parent_free_goal;
    parent.rho.assign(ins.n_robots(), -1);
    for (size_t i = 0; i < ins.n_robots(); ++i)
      if ((*parent_free_goal)[i] >= 0) parent.rho[i] = 0;  // any valid idx
    pg = &parent;
  }
  Node node;
  node.X = X;
  scratch.occ_node = nullptr;
  scratch.pibt_node = nullptr;
  node.guide = build_guidance(ins, node.X, target_goal_dist, lower_dist,
                              path_cache, scratch, &node, park_registry,
                              nullptr, pg);
  return node.guide.free_goal;
}

std::vector<int> dd_least_blocking_path(const DDGrid& g, int src, int dst,
                                        const std::vector<uint8_t>& occupied,
                                        const std::vector<int>* prev_path)
{
  Scratch sc(g.size());
  return least_blocking_path(g, src, dst, occupied, /*exclude=*/-1, sc,
                             prev_path);
}


std::vector<Op> dd_root_joint_ops(const DDInstance& ins, const PhysConfig& X,
                                  int seed)
{
  std::mt19937 rng(seed);
  std::vector<DistCache> target_goal_dist;
  target_goal_dist.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b)
    target_goal_dist.emplace_back(ins.grid);
  LowerDist lower_dist(ins.grid);
  PathCache path_cache;
  Scratch scratch(ins.grid.size());
  std::vector<int> park_registry(ins.n_targets(), -1);
  Node node;
  node.X = X;
  scratch.occ_node = nullptr;
  scratch.pibt_node = nullptr;
  node.guide = build_guidance(ins, node.X, target_goal_dist, lower_dist,
                              path_cache, scratch, &node, park_registry);
  node.order = make_order(ins, node.X, node.guide, target_goal_dist);
  node.constraint_order = node.order;
  Constraint root;
  auto res = carrier_pibt(ins, node, &root, target_goal_dist, lower_dist,
                          rng, scratch, nullptr);
  if (!res.has_value()) return {};
  return res->second;
}

std::vector<int> dd_waitfor_cycle_robots(const DDInstance& ins,
                                         const PhysConfig& X)
{
  std::vector<DistCache> target_goal_dist;
  target_goal_dist.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b)
    target_goal_dist.emplace_back(ins.grid);
  LowerDist lower_dist(ins.grid);
  PathCache path_cache;
  Scratch scratch(ins.grid.size());
  std::vector<int> park_registry(ins.n_targets(), -1);
  Node node;
  node.X = X;
  scratch.occ_node = nullptr;
  scratch.pibt_node = nullptr;
  node.guide = build_guidance(ins, node.X, target_goal_dist, lower_dist,
                              path_cache, scratch, &node, park_registry);
  scratch.occ_node = nullptr;
  fill_occupancy(ins, node.X, scratch);
  return waitfor_cycles(ins, node.X, node.guide, lower_dist, scratch);
}

int dd_parking_cell(const DDInstance& ins, const PhysConfig& X, int robot)
{
  std::vector<DistCache> target_goal_dist;
  target_goal_dist.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b)
    target_goal_dist.emplace_back(ins.grid);
  LowerDist lower_dist(ins.grid);
  PathCache path_cache;
  Scratch scratch(ins.grid.size());
  std::vector<int> park_registry(ins.n_targets(), -1);
  Node node;
  node.X = X;
  scratch.occ_node = nullptr;
  scratch.pibt_node = nullptr;
  node.guide = build_guidance(ins, node.X, target_goal_dist, lower_dist,
                              path_cache, scratch, &node, park_registry);
  return node.guide.parking_cell[robot];
}
