// Carrier-LaCAM planner (design.md section 5, milestone M1).
//
// High-level: LaCAM-style DFS over physical configurations with lazy
// operator-level constraint trees (5.2).  Successors are generated by
// Carrier-PIBT (5.4) with greedy rho matching of free robots to serve/clear
// requests (5.3).  The dd_carrier validator is the final arbiter for every
// generated joint operator vector (G1).
#include "../include/dd_planner.hpp"

#include <algorithm>
#include <chrono>
#include <climits>
#include <cstring>
#include <deque>
#include <memory>
#include <queue>
#include <random>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace {

using Clock = std::chrono::steady_clock;

// ---------- distance fields ----------
// BFS over walls only; returns dist vector (INT_MAX/2 unreachable)
std::vector<int> bfs_dist(const DDGrid& g, int src)
{
  std::vector<int> d(g.size(), INT_MAX / 2);
  std::deque<int> dq;
  d[src] = 0;
  dq.push_back(src);
  int nb[4];
  while (!dq.empty()) {
    int u = dq.front();
    dq.pop_front();
    const int n = g.neighbors(u, nb);
    for (int k = 0; k < n; ++k)
      if (d[nb[k]] > d[u] + 1) {
        d[nb[k]] = d[u] + 1;
        dq.push_back(nb[k]);
      }
  }
  return d;
}

struct DistCache {
  const DDGrid& g;
  std::unordered_map<int, std::vector<int>> by_src;
  explicit DistCache(const DDGrid& g_) : g(g_) {}
  const std::vector<int>& to(int cell)
  {
    auto it = by_src.find(cell);
    if (it == by_src.end())
      it = by_src.emplace(cell, bfs_dist(g, cell)).first;
    return it->second;
  }
};

// ---------- least-blocking path (design 5.3(2)) ----------
// deque-based small-weight Dijkstra: step cost 1 + LAMBDA_BLK * occupied(to).
constexpr int LAMBDA_BLK = 8;

// grid-sized scratch buffers reused across nodes (single-threaded planner)
struct Scratch {
  std::vector<uint8_t> upper;    // upper-deck occupancy flags (per node)
  std::vector<uint8_t> protect;  // protected path/goal cells (per node)
  std::vector<int> grounded;     // 0 none; -1 anon; b+1 grounded target b
  std::vector<int> owner;        // path owner b+1 (per node)
  std::vector<int> dist;         // dijkstra dist / bfs visited
  std::vector<int> prev;         // dijkstra parents
  std::vector<int> upper_base;   // grounded+anon counts for PIBT baseline
  const void* occ_node = nullptr;
  const void* pibt_node = nullptr;
  explicit Scratch(int n)
      : upper(n, 0), protect(n, 0), grounded(n, 0), owner(n, 0), dist(n),
        prev(n), upper_base(n, 0) {}
};

void fill_occupancy(const DDInstance& ins, const PhysConfig& s, Scratch& sc)
{
  std::fill(sc.upper.begin(), sc.upper.end(), 0);
  std::fill(sc.grounded.begin(), sc.grounded.end(), 0);
  for (int p : s.anon_occ) {
    sc.upper[p] = 1;
    sc.grounded[p] = -1;
  }
  std::vector<bool> carried(ins.n_targets(), false);
  for (int k : s.kappa)
    if (k >= 0) carried[k] = true;
  for (size_t b = 0; b < ins.n_targets(); ++b) {
    sc.upper[s.target_pos[b]] = 1;
    if (!carried[b]) sc.grounded[s.target_pos[b]] = (int)b + 1;
  }
  for (size_t i = 0; i < s.kappa.size(); ++i)
    if (s.kappa[i] == KAPPA_ANON) sc.upper[s.robots[i]] = 1;
}

void fill_occupancy_if_needed(const DDInstance& ins, const PhysConfig& s,
                              Scratch& sc, const void* key)
{
  if (sc.occ_node == key && key != nullptr) return;
  fill_occupancy(ins, s, sc);
  sc.occ_node = key;
}

std::vector<int> least_blocking_path(const DDGrid& g, int src, int dst,
                                     const std::vector<uint8_t>& occupied,
                                     int exclude, Scratch& sc)
{
  if (src == dst) return {src};
  std::fill(sc.dist.begin(), sc.dist.end(), INT_MAX / 2);
  auto& dist = sc.dist;
  auto& prev = sc.prev;
  prev[src] = -1;
  using QE = std::pair<int, int>;  // (dist, cell)
  std::priority_queue<QE, std::vector<QE>, std::greater<QE>> pq;
  dist[src] = 0;
  pq.push({0, src});
  int nb[4];
  while (!pq.empty()) {
    auto [d, u] = pq.top();
    pq.pop();
    if (d > dist[u]) continue;
    if (u == dst) break;
    const int n = g.neighbors(u, nb);
    for (int k = 0; k < n; ++k) {
      const int v = nb[k];
      const bool occ = v != exclude && occupied[v];
      const int w = 1 + (occ ? LAMBDA_BLK : 0);
      if (dist[v] > d + w) {
        dist[v] = d + w;
        prev[v] = u;
        pq.push({dist[v], v});
      }
    }
  }
  if (dist[dst] >= INT_MAX / 2) return {};
  std::vector<int> path;
  for (int c = dst; c != -1; c = prev[c]) path.push_back(c);
  std::reverse(path.begin(), path.end());
  return path;
}

// per-target cached least-blocking path with lazy invalidation (design 6.2):
// valid while the target position matches and the occupancy status of every
// path cell is unchanged.
struct PathCache {
  struct Entry {
    std::vector<int> path;
    std::vector<uint8_t> occ_snapshot;  // occupied flag per path cell
    int src = -1;
  };
  std::unordered_map<int, Entry> by_target;

  const std::vector<int>& get(const DDGrid& g, int b, int src, int dst,
                              const std::vector<uint8_t>& occupied,
                              int exclude, Scratch& sc)
  {
    auto it = by_target.find(b);
    if (it != by_target.end()) {
      auto& e = it->second;
      // incremental head-advance: the carrier moved one step along the path
      if (e.src != src && e.path.size() >= 2 && e.path[1] == src) {
        e.path.erase(e.path.begin());
        e.occ_snapshot.erase(e.occ_snapshot.begin());
        e.src = src;
        // the new head is the target itself now: mark unoccupied
        if (!e.occ_snapshot.empty()) e.occ_snapshot[0] = 0;
      }
      if (e.src == src) {
        bool ok = true;
        for (size_t i = 0; i < e.path.size() && ok; ++i) {
          const int c = e.path[i];
          const bool occ_now = c != exclude && occupied[c];
          ok = (occ_now == (e.occ_snapshot[i] != 0));
        }
        if (ok) return e.path;
      }
    }
    Entry e;
    e.src = src;
    e.path = least_blocking_path(g, src, dst, occupied, exclude, sc);
    e.occ_snapshot.resize(e.path.size());
    for (size_t i = 0; i < e.path.size(); ++i) {
      const int c = e.path[i];
      e.occ_snapshot[i] = (c != exclude && occupied[c]) ? 1 : 0;
    }
    auto res = by_target.insert_or_assign(b, std::move(e));
    return res.first->second.path;
  }
};

// ---------- requests & guidance (design 5.3, M1 greedy) ----------
struct Request {
  enum Kind { SERVE, CLEAR } kind;
  int target = -1;   // for SERVE: target idx; for CLEAR: blocking cell owner
  int cell = -1;     // shelf cell to lift (serve: target pos; clear: blocker)
  int priority = 0;  // higher first (chain head highest)
};

struct Guidance {
  std::vector<Request> requests;
  // rho: robot -> request index (or -1)
  std::vector<int> rho;
  // per-robot goal cell for free robots (request cell)
  std::vector<int> free_goal;
  std::vector<int> parking_cell;  // for ANON carriers: chosen parking cell
  // per-target: next cell along its least-blocking path (guidance for the
  // carrier), -1 if none
  std::vector<int> target_next;
  // per-target: true when the target's goal lies on ANOTHER unfinished
  // target's active path — its carrier must PARK it (clear semantics)
  // instead of delivering into the busy corridor (design 5.3 clear).
  // Sticky (hysteresis, design 5.3(4)): once parked for owner b, stays
  // parked until b completes, preventing deliver/park flip-flop.
  std::vector<uint8_t> target_park;
  std::vector<int> park_owner;  // target idx whose path forced the park
};

struct Node;
using NodePtr = Node*;

// operator constraint (design 5.2): partial assignment robot -> Op
struct Constraint {
  Constraint* parent = nullptr;
  int depth = 0;  // number of robots fixed
  int who = -1;
  Op what;
  std::vector<std::unique_ptr<Constraint>> kids;  // owned by node tree root
};

struct Node {
  PhysConfig X;
  Node* parent = nullptr;
  std::vector<int> order;  // PIBT priority order (robot ids)
  std::unique_ptr<Constraint> tree_root;
  std::deque<Constraint*> tree_open;  // FIFO within node (LaCAM style)
  Guidance guide;
  int depth = 0;
  // M1 livelock signal (design 5.5): monotone best guidance-h along the
  // parent chain + steps since last improvement
  long h_guidance = 0;
  long best_h = 0;
  int no_progress = 0;
  int revisits = 0;  // duplicate-successor re-pushes (livelock indicator)
};

// upper-deck occupancy set of a config (grounded + carried-at-cell)
std::unordered_set<int> upper_cells(const DDInstance& ins, const PhysConfig& s)
{
  std::unordered_set<int> up(s.anon_occ.begin(), s.anon_occ.end());
  for (size_t b = 0; b < ins.n_targets(); ++b) up.insert(s.target_pos[b]);
  for (size_t i = 0; i < s.kappa.size(); ++i)
    if (s.kappa[i] == KAPPA_ANON) up.insert(s.robots[i]);
  return up;
}

// grounded shelf at cell? (target idx >=0, ANON -2, none -1... encode)
struct GroundedIndex {
  std::unordered_map<int, int> target_at;  // cell -> target idx
  std::unordered_set<int> anon_at;
  GroundedIndex(const DDInstance& ins, const PhysConfig& s)
  {
    std::vector<bool> carried(ins.n_targets(), false);
    for (int k : s.kappa)
      if (k >= 0) carried[k] = true;
    for (size_t b = 0; b < ins.n_targets(); ++b)
      if (!carried[b]) target_at[s.target_pos[b]] = (int)b;
    anon_at.insert(s.anon_occ.begin(), s.anon_occ.end());
  }
};

// ---------- guidance construction ----------
constexpr int CLEAR_CHAIN_K = 3;

Guidance build_guidance(const DDInstance& ins, const PhysConfig& s,
                        std::vector<DistCache>& target_goal_dist,
                        DistCache& lower_dist, PathCache& paths, Scratch& sc,
                        const void* node_key,
                        const std::vector<std::pair<int, int>>* taboo = nullptr,
                        const Guidance* parent = nullptr)
{
  Guidance g;
  const size_t R = ins.n_robots();
  fill_occupancy_if_needed(ins, s, sc, node_key);
  std::fill(sc.protect.begin(), sc.protect.end(), 0);
  std::fill(sc.owner.begin(), sc.owner.end(), 0);
  g.target_next.assign(ins.n_targets(), -1);

  // least-blocking paths (cached) drive serve/clear requests, carrier
  // guidance, and the protected set.
  g.target_park.assign(ins.n_targets(), 0);
  for (size_t b = 0; b < ins.n_targets(); ++b) {
    bool carried =
        std::any_of(s.kappa.begin(), s.kappa.end(),
                    [&](int k) { return k == (int)b; });
    const bool done = !carried && s.target_pos[b] == ins.target_goals[b];
    if (done) continue;
    // occupancy for this target's path: every upper cell except itself
    const auto& path = paths.get(ins.grid, (int)b, s.target_pos[b],
                                 ins.target_goals[b], sc.upper,
                                 s.target_pos[b], sc);
    if (path.size() >= 2) g.target_next[b] = path[1];
    for (int c : path) {
      sc.protect[c] = 1;
      if (sc.owner[c] == 0) sc.owner[c] = (int)b + 1;
    }

    // design 5.3: serve(b) only when the FIRST path cell is empty on the
    // upper deck; otherwise emit clear requests for the leading blockers.
    const bool head_free = path.size() >= 2 && sc.grounded[path[1]] == 0;
    if (!carried && head_free) {
      Request r;
      r.kind = Request::SERVE;
      r.target = (int)b;
      r.cell = s.target_pos[b];
      r.priority = 100;
      g.requests.push_back(r);
    }
    int emitted = 0;
    for (size_t pi = 1; pi < path.size() && emitted < CLEAR_CHAIN_K; ++pi) {
      const int cur = path[pi];
      const int gr__ = sc.grounded[cur];
      if (gr__ == -1 || (gr__ > 0 && gr__ - 1 != (int)b)) {
        Request r;
        r.kind = Request::CLEAR;
        r.target = (int)b;
        r.cell = cur;
        r.priority = 50 - emitted;  // chain head higher
        g.requests.push_back(r);
        ++emitted;
      }
    }
  }
  // every target goal is protected against parking: a completed target
  // parked back onto a pending goal is the classic serve/clear livelock.
  for (size_t b = 0; b < ins.n_targets(); ++b)
    sc.protect[ins.target_goals[b]] = 1;

  // clear semantics for carried targets whose goal sits on ANOTHER
  // unfinished target's path: park instead of delivering into the corridor.
  g.park_owner.assign(ins.n_targets(), -1);
  auto target_done = [&](int b) {
    if (s.target_pos[b] != ins.target_goals[b]) return false;
    for (int k : s.kappa)
      if (k == b) return false;
    return true;
  };
  for (size_t b = 0; b < ins.n_targets(); ++b) {
    const int ow__ = sc.owner[ins.target_goals[b]];
    if (ow__ > 0 && ow__ - 1 != (int)b) {
      g.target_park[b] = 1;
      g.park_owner[b] = ow__ - 1;
    }
  }
  // sticky park (hysteresis): inherit parent's park until the owner is done
  if (parent && !parent->target_park.empty()) {
    for (size_t b = 0; b < ins.n_targets(); ++b) {
      if (g.target_park[b] || !parent->target_park[b]) continue;
      const int owner = parent->park_owner[b];
      if (owner >= 0 && !target_done(owner)) {
        g.target_park[b] = 1;
        g.park_owner[b] = owner;
      }
    }
  }

  // rho: greedy nearest free robot per request (priority order)
  g.rho.assign(R, -1);
  g.free_goal.assign(R, -1);
  g.parking_cell.assign(R, -1);
  std::vector<int> req_order(g.requests.size());
  for (size_t i = 0; i < req_order.size(); ++i) req_order[i] = (int)i;
  std::stable_sort(req_order.begin(), req_order.end(), [&](int a, int b) {
    return g.requests[a].priority > g.requests[b].priority;
  });
  std::vector<bool> robot_used(R, false);
  int free_left = 0;
  for (size_t i = 0; i < R; ++i) {
    if (s.kappa[i] != KAPPA_FREE)
      robot_used[i] = true;
    else
      ++free_left;
  }
  for (int ri : req_order) {
    if (free_left == 0) break;
    const auto& req = g.requests[ri];
    const auto& dl = lower_dist.to(req.cell);
    int best = -1, bestd = INT_MAX / 2;
    for (size_t i = 0; i < R; ++i) {
      if (robot_used[i]) continue;
      if (taboo) {
        bool banned = false;
        for (auto& [rb, cell] : *taboo)
          banned |= (rb == (int)i && cell == req.cell);
        if (banned) continue;
      }
      if (dl[s.robots[i]] < bestd) {
        bestd = dl[s.robots[i]];
        best = (int)i;
      }
    }
    if (best >= 0) {
      robot_used[best] = true;
      --free_left;
      g.rho[best] = ri;
      g.free_goal[best] = req.cell;
    }
  }

  // parking placement: nearest free cell off every active least-blocking
  // path (protected) with goal-cell fallback.  NOTE: design 5.6 margin/
  // corridor scoring was tried and HURT dense instances (d50 regression);
  // revisit with M2 deadlock machinery.
  std::vector<uint8_t> is_goal_cell(ins.grid.size(), 0);
  for (size_t b = 0; b < ins.n_targets(); ++b)
    is_goal_cell[ins.target_goals[b]] = 1;
  for (size_t i = 0; i < R; ++i) {
    const bool anon_carrier = s.kappa[i] == KAPPA_ANON;
    const bool parked_target_carrier =
        s.kappa[i] >= 0 && g.target_park[s.kappa[i]];
    if (!anon_carrier && !parked_target_carrier) continue;
    int found = -1, fallback = -1;
    std::fill(sc.prev.begin(), sc.prev.end(), 0);  // visited flags
    std::deque<int> dq;
    dq.push_back(s.robots[i]);
    sc.prev[s.robots[i]] = 1;
    int nb[4];
    while (!dq.empty() && found < 0) {
      int u = dq.front();
      dq.pop_front();
      if (u != s.robots[i] && !sc.upper[u]) {
        if (!sc.protect[u]) {
          found = u;
          break;
        }
        if (fallback < 0 && !is_goal_cell[u]) fallback = u;
      }
      const int n = ins.grid.neighbors(u, nb);
      for (int k = 0; k < n; ++k)
        if (!sc.prev[nb[k]]) {
          sc.prev[nb[k]] = 1;
          dq.push_back(nb[k]);
        }
    }
    g.parking_cell[i] = found >= 0 ? found : fallback;
  }
  return g;
}

// priority order (design 5.4 N.order): loaded-target > loaded-ANON >
// free assigned > free idle; tie-break by remaining distance then id.
std::vector<int> make_order(const DDInstance& ins, const PhysConfig& s,
                            const Guidance& g,
                            std::vector<DistCache>& target_goal_dist)
{
  const size_t R = ins.n_robots();
  std::vector<int> order(R);
  for (size_t i = 0; i < R; ++i) order[i] = (int)i;
  auto cls = [&](int i) {
    if (s.kappa[i] >= 0)
      return g.target_park[s.kappa[i]] ? 1 : 0;  // parked duty ~ clear duty
    if (s.kappa[i] == KAPPA_ANON) return 1;
    if (g.rho[i] >= 0) return 2;
    return 3;
  };
  auto rem = [&](int i) -> int {
    if (s.kappa[i] >= 0) {
      const auto& d = target_goal_dist[s.kappa[i]].to(
          ins.target_goals[s.kappa[i]]);
      return d[s.robots[i]];
    }
    if (g.free_goal[i] >= 0) return 0;  // handled by class
    return 0;
  };
  std::stable_sort(order.begin(), order.end(), [&](int a, int b) {
    const int ca = cls(a), cb = cls(b);
    if (ca != cb) return ca < cb;
    const int ra = rem(a), rb = rem(b);
    if (ra != rb) return ra < rb;
    return a < b;
  });
  return order;
}

// ---------- Carrier-PIBT (design 5.4) ----------
struct PIBTContext {
  const DDInstance& ins;
  const PhysConfig& s;
  const Guidance& g;
  std::vector<DistCache>& target_goal_dist;
  DistCache& lower_dist;
  std::mt19937& rng;
  // occupancy bookkeeping for the NEXT config being built
  std::vector<Op> ops;              // per robot; kind==WAIT&&to==-2 -> unset
  std::vector<int> next_cell;       // -1 unset
  std::unordered_map<int, int> next_owner;  // next cell -> robot
  std::unordered_map<int, int> upper_cnt;   // DELTAS on top of sc.upper_base
  Scratch& sc;

  void upper_add(int v) { upper_cnt[v]++; }
  void upper_remove(int v)
  {
    auto it = upper_cnt.find(v);
    if (it != upper_cnt.end() && --it->second == 0) upper_cnt.erase(it);
  }
  bool upper_taken(int v) const
  {
    int cnt = sc.upper_base[v];
    auto it = upper_cnt.find(v);
    if (it != upper_cnt.end()) cnt += it->second;
    return cnt > 0;
  }

  PIBTContext(const DDInstance& ins_, const PhysConfig& s_,
              const Guidance& g_, std::vector<DistCache>& tgd,
              DistCache& ld, std::mt19937& rng_, Scratch& sc_,
              const void* node_key)
      : ins(ins_), s(s_), g(g_), target_goal_dist(tgd), lower_dist(ld),
        rng(rng_), sc(sc_)
  {
    const size_t R = ins.n_robots();
    ops.assign(R, Op{Op::WAIT, -2});
    next_cell.assign(R, -1);
    fill_occupancy_if_needed(ins, s, sc, node_key);
    if (sc.pibt_node != node_key) {
      // per-node baseline: grounded (target+anon) shelves occupy their
      // cells at t+1; carried shelves are registered via deltas on fix.
      std::fill(sc.upper_base.begin(), sc.upper_base.end(), 0);
      for (int p : s.anon_occ) sc.upper_base[p] = 1;
      std::vector<bool> carried__(ins.n_targets(), false);
      for (int k : s.kappa)
        if (k >= 0) carried__[k] = true;
      for (size_t b = 0; b < ins.n_targets(); ++b)
        if (!carried__[b]) sc.upper_base[s.target_pos[b]] = 1;
      sc.pibt_node = node_key;
    }
  }

  bool cell_taken(int v) const { return next_owner.count(v) > 0; }

  bool swap_conflict(int i, int to) const
  {
    // moving i: s.robots[i] -> to; conflict if some j already fixed with
    // next=s.robots[i] and s.robots[j]==to
    auto it = next_owner.find(s.robots[i]);
    if (it == next_owner.end()) return false;
    const int j = it->second;
    return j != i && s.robots[j] == to;
  }

  // candidate ops for robot i in preference order (design 5.4 table)
  std::vector<Op> candidates(int i)
  {
    std::vector<Op> cand;
    const int q = s.robots[i];
    int nb[4];
    const int n = ins.grid.neighbors(q, nb);
    const int k = s.kappa[i];

    auto push_moves_sorted_by = [&](const std::vector<int>& dist,
                                    bool loaded) {
      std::vector<int> cells(nb, nb + n);
      std::shuffle(cells.begin(), cells.end(), rng);
      std::stable_sort(cells.begin(), cells.end(),
                       [&](int a, int b) { return dist[a] < dist[b]; });
      for (int v : cells) {
        if (loaded) {
          // S1 pre-filter: destination upper cell free so far
          if (upper_taken(v)) continue;
        }
        cand.push_back(Op::make_move(v));
      }
    };

    if (k >= 0 && !g.target_park[k]) {
      // loaded with target k
      const auto& d = target_goal_dist[k].to(ins.target_goals[k]);
      if (q == ins.target_goals[k]) {
        cand.push_back(Op::make_drop());
        cand.push_back(Op::make_wait());
        return cand;
      }
      // primary: next cell on the least-blocking path (if legal now)
      const int nxt_cell = g.target_next[k];
      if (nxt_cell >= 0 && !upper_taken(nxt_cell)) {
        for (int t2 = 0; t2 < n; ++t2)
          if (nb[t2] == nxt_cell) {
            cand.push_back(Op::make_move(nxt_cell));
            break;
          }
      }
      push_moves_sorted_by(d, /*loaded=*/true);
      // dedupe: drop a duplicate of nxt_cell if present
      if (cand.size() >= 2)
        for (size_t a = 1; a < cand.size(); ++a)
          if (cand[a] == cand[0]) {
            cand.erase(cand.begin() + a);
            break;
          }
      // design 5.4: Drop as a yield when the path head is STRUCTURALLY
      // blocked (grounded shelf), freeing this robot to serve clears.
      const bool structurally_blocked =
          nxt_cell >= 0 && sc.grounded[nxt_cell] != 0;
      if (structurally_blocked) {
        cand.push_back(Op::make_drop());
        cand.push_back(Op::make_wait());
      } else {
        cand.push_back(Op::make_wait());
        cand.push_back(Op::make_drop());  // last resort: yield
      }
    } else if (k == KAPPA_ANON || (k >= 0 && g.target_park[k])) {
      const int park = g.parking_cell[i];
      if (park == q) {
        cand.push_back(Op::make_drop());
        cand.push_back(Op::make_wait());
        return cand;
      }
      if (park >= 0) {
        const auto& d = lower_dist.to(park);
        push_moves_sorted_by(d, /*loaded=*/true);
      } else {
        // no parking known: any legal loaded move
        std::vector<int> zero(ins.grid.size(), 0);
        push_moves_sorted_by(zero, /*loaded=*/true);
      }
      // drop is the last resort (validator-checked); wait before drop
      cand.push_back(Op::make_wait());
      cand.push_back(Op::make_drop());
    } else {
      // free robot
      const int goal = g.free_goal[i];
      if (goal >= 0 && q == goal) {
        // at request cell: lift if grounded shelf present
        if (sc.grounded[q] != 0) cand.push_back(Op::make_lift());
      }
      if (goal >= 0) {
        const auto& d = lower_dist.to(goal);
        push_moves_sorted_by(d, /*loaded=*/false);
        cand.push_back(Op::make_wait());
      } else {
        // idle: prefer to stay put; move only when pushed (M1 avoidance)
        cand.push_back(Op::make_wait());
        std::vector<int> zero(ins.grid.size(), 0);
        push_moves_sorted_by(zero, /*loaded=*/false);
      }
    }
    return cand;
  }

  // try to fix robot i to op; returns false on conflict with already-fixed
  bool feasible(int i, const Op& op) const
  {
    int to = s.robots[i];
    if (op.kind == Op::MOVE) to = op.to;
    if (cell_taken(to)) return false;
    if (op.kind == Op::MOVE && swap_conflict(i, op.to)) return false;
    if (op.kind == Op::MOVE && s.kappa[i] != KAPPA_FREE) {
      // S1: carried shelf enters `to` at t+1
      if (upper_taken(to)) return false;
    }
    if (op.kind == Op::LIFT) {
      if (sc.grounded[to] == 0) return false;
    }
    if (op.kind == Op::DROP && s.kappa[i] == KAPPA_ANON) {
      // the carried ANON shelf itself is not registered until fixed, so any
      // count at q belongs to ANOTHER shelf -> S1
      if (upper_taken(to)) return false;
    }
    return true;
  }

  // exact upper-deck bookkeeping delta for fixing robot i to op:
  // grounded shelves are pre-registered; a LIFTED shelf stays at its cell
  // (already counted).  A carried shelf occupies `to` at t+1 for
  // WAIT/MOVE/DROP.
  bool carried_occupies(const Op& op, int i) const
  {
    return s.kappa[i] != KAPPA_FREE &&
           (op.kind == Op::WAIT || op.kind == Op::MOVE ||
            op.kind == Op::DROP);
  }

  void fix(int i, const Op& op)
  {
    int to = s.robots[i];
    if (op.kind == Op::MOVE) to = op.to;
    ops[i] = op;
    next_cell[i] = to;
    next_owner[to] = i;
    if (carried_occupies(op, i)) upper_add(to);
  }

  void unfix(int i, const Op& op)
  {
    int to = s.robots[i];
    if (op.kind == Op::MOVE) to = op.to;
    next_owner.erase(to);
    next_cell[i] = -1;
    ops[i] = Op{Op::WAIT, -2};
    if (carried_occupies(op, i)) upper_remove(to);
  }
};

// recursive PIBT: fix robot i (priority index), pushing occupants
bool pibt_fix(PIBTContext& ctx, const std::vector<int>& order, int i,
              const std::vector<Op>* forced, int depth_guard)
{
  if (depth_guard > (int)ctx.ins.n_robots() * 4) return false;
  const int robot = order[i];
  if (ctx.next_cell[robot] != -1) return true;  // already fixed

  std::vector<Op> cand;
  if (forced && !((*forced)[robot] == Op{Op::WAIT, -2})) {
    cand = {(*forced)[robot]};
  } else {
    cand = ctx.candidates(robot);
  }
  for (const Op& op : cand) {
    if (!ctx.feasible(robot, op)) continue;
    // standard PIBT: if MOVE destination currently hosts an UNDECIDED robot,
    // fix us tentatively and immediately recurse on the occupant; backtrack
    // to our next candidate if the occupant cannot be placed.
    int occupant = -1;
    if (op.kind == Op::MOVE) {
      for (size_t j = 0; j < ctx.ins.n_robots(); ++j)
        if ((int)j != robot && ctx.s.robots[j] == op.to &&
            ctx.next_cell[j] == -1) {
          occupant = (int)j;
          break;
        }
    }
    ctx.fix(robot, op);
    if (occupant >= 0) {
      int occ_pos = -1;
      for (size_t k2 = 0; k2 < order.size(); ++k2)
        if (order[k2] == occupant) occ_pos = (int)k2;
      if (occ_pos < 0 ||
          !pibt_fix(ctx, order, occ_pos, forced, depth_guard + 1)) {
        ctx.unfix(robot, op);
        continue;
      }
    }
    return true;
  }
  // last resort: wait (if wait cell not taken by someone else this step)
  Op w = Op::make_wait();
  if (ctx.feasible(robot, w)) {
    ctx.fix(robot, w);
    return true;
  }
  return false;
}

// generate successor configuration honoring constraint chain (nullopt if
// generator failed — allowed under partial constraints, G1)
std::optional<std::pair<PhysConfig, std::vector<Op>>> carrier_pibt(
    const DDInstance& ins, Node& node, Constraint* c,
    std::vector<DistCache>& tgd, DistCache& ld, std::mt19937& rng,
    Scratch& sc, DDStats* stats)
{
  const size_t R = ins.n_robots();
  // collect forced ops from constraint chain
  std::vector<Op> forced(R, Op{Op::WAIT, -2});
  for (Constraint* p = c; p && p->depth > 0; p = p->parent)
    forced[p->who] = p->what;

  PIBTContext ctx(ins, node.X, node.guide, tgd, ld, rng, sc, &node);
  if (stats) stats->pibt_calls++;

  // apply forced ops first (in priority order among forced robots)
  for (int r : node.order) {
    if (!(forced[r] == Op{Op::WAIT, -2})) {
      if (!ctx.feasible(r, forced[r])) {
        if (stats) stats->generator_failures++;
        return std::nullopt;
      }
      ctx.fix(r, forced[r]);
    }
  }
  for (size_t i = 0; i < R; ++i) {
    if (!pibt_fix(ctx, node.order, (int)i, &forced, 0)) {
      if (stats) stats->generator_failures++;
      return std::nullopt;
    }
  }
  // normalize unset ops (shouldn't happen) to WAIT
  for (size_t i = 0; i < R; ++i)
    if (ctx.ops[i].kind == Op::WAIT && ctx.ops[i].to == -2)
      ctx.ops[i] = Op::make_wait();

  // FINAL ARBITER (G1): the two-deck validator
  auto nxt = apply_ops(ins, node.X, ctx.ops);
  if (!nxt.has_value()) {
    if (stats) stats->validator_rejects++;
    return std::nullopt;
  }
  return std::make_pair(*nxt, ctx.ops);
}

// enumerate legal local ops of robot r at node (design 5.2 branching)
std::vector<Op> legal_local_ops(const DDInstance& ins, const PhysConfig& s,
                                int r, Scratch& sc, const void* node_key)
{
  fill_occupancy_if_needed(ins, s, sc, node_key);
  std::vector<Op> out;
  const int q = s.robots[r];
  out.push_back(Op::make_wait());
  int nb[4];
  const int n = ins.grid.neighbors(q, nb);
  for (int k = 0; k < n; ++k) out.push_back(Op::make_move(nb[k]));
  if (s.kappa[r] == KAPPA_FREE) {
    if (sc.grounded[q] != 0) out.push_back(Op::make_lift());
  } else {
    out.push_back(Op::make_drop());
  }
  return out;
}

}  // namespace

DDPlan solve_carrier_lacam(const DDInstance& ins, double time_limit_sec,
                           int seed, DDStats* stats, DDPlan* best_effort)
{
  const auto t_start = Clock::now();
  auto expired = [&]() {
    return std::chrono::duration<double>(Clock::now() - t_start).count() >
           time_limit_sec;
  };
  std::mt19937 rng(seed);
  const size_t R = ins.n_robots();

  // distance caches: per target goal field (upper wall-only) + lower fields
  std::vector<DistCache> target_goal_dist;
  target_goal_dist.reserve(ins.n_targets());
  for (size_t b = 0; b < ins.n_targets(); ++b)
    target_goal_dist.emplace_back(ins.grid);
  DistCache lower_dist(ins.grid);
  PathCache path_cache;
  Scratch scratch(ins.grid.size());

  // node storage
  std::deque<std::unique_ptr<Node>> all_nodes;
  std::unordered_map<PhysConfig, Node*, PhysConfigHasher> explored;
  // parent op edge for solution extraction
  std::unordered_map<Node*, std::pair<Node*, std::vector<Op>>> parent_edge;

  // guidance-h: sum over unfinished targets of goal distance (+2 lift/drop
  // proxy).  Ordering-only signal for the livelock detector; the O(B*R)
  // approach term was dropped for throughput.
  auto guidance_h = [&](const PhysConfig& X) -> long {
    long h = 0;
    for (size_t b = 0; b < ins.n_targets(); ++b) {
      bool carried = false;
      for (int k : X.kappa) carried |= (k == (int)b);
      const bool done = !carried && X.target_pos[b] == ins.target_goals[b];
      if (done) continue;
      const auto& d = target_goal_dist[b].to(ins.target_goals[b]);
      h += d[X.target_pos[b]] + 2;
    }
    return h;
  };
  constexpr int LIVELOCK_WINDOW = 24;

  auto make_node = [&](PhysConfig&& X, Node* parent) -> Node* {
    all_nodes.push_back(std::make_unique<Node>());
    Node* nd = all_nodes.back().get();
    nd->X = std::move(X);
    nd->parent = parent;
    nd->depth = parent ? parent->depth + 1 : 0;
    nd->h_guidance = guidance_h(nd->X);
    nd->best_h = parent ? std::min(parent->best_h, nd->h_guidance)
                        : nd->h_guidance;
    nd->no_progress =
        (parent && nd->h_guidance >= parent->best_h) ? parent->no_progress + 1
                                                     : 0;
    // M1 livelock signal (design 5.5): no guidance-h improvement for a
    // window -> shuffle order within classes + taboo the parent's rho pairs
    std::vector<std::pair<int, int>> taboo;
    const bool livelock = nd->no_progress > 0 &&
                          nd->no_progress % LIVELOCK_WINDOW == 0;
    if (livelock && parent) {
      for (size_t i = 0; i < ins.n_robots(); ++i)
        if (parent->guide.rho[i] >= 0)
          taboo.emplace_back((int)i, parent->guide.free_goal[i]);
    }
    nd->guide = build_guidance(ins, nd->X, target_goal_dist, lower_dist,
                               path_cache, scratch, nd,
                               livelock ? &taboo : nullptr,
                               parent ? &parent->guide : nullptr);
    nd->order = make_order(ins, nd->X, nd->guide, target_goal_dist);
    if (livelock) {
      // shuffle within equal-priority classes only: order was built with
      // stable sort by (class, rem, id); shuffle whole order but re-sort by
      // class keeps classes, randomizes within.
      std::shuffle(nd->order.begin(), nd->order.end(), rng);
      std::stable_sort(nd->order.begin(), nd->order.end(),
                       [&](int a, int b) {
                         auto cls = [&](int i) {
                           if (nd->X.kappa[i] >= 0) return 0;
                           if (nd->X.kappa[i] == KAPPA_ANON) return 1;
                           if (nd->guide.rho[i] >= 0) return 2;
                           return 3;
                         };
                         return cls(a) < cls(b);
                       });
    }
    nd->tree_root = std::make_unique<Constraint>();
    nd->tree_open.push_back(nd->tree_root.get());
    if (stats) {
      stats->hl_nodes++;
      if (nd->depth > stats->max_depth) {
        stats->max_depth = nd->depth;
        stats->deepest_config = nd->X;
      }
      long done = 0;
      for (size_t b = 0; b < ins.n_targets(); ++b) {
        bool carried = false;
        for (int k : nd->X.kappa) carried |= (k == (int)b);
        if (!carried && nd->X.target_pos[b] == ins.target_goals[b]) ++done;
      }
      stats->best_targets_done = std::max(stats->best_targets_done, done);
    }
    return nd;
  };

  auto extract_plan = [&](Node* nd) {
    DDPlan plan;
    for (Node* cur = nd; cur && parent_edge.count(cur);) {
      auto& [p, ops] = parent_edge[cur];
      plan.push_back(ops);
      cur = p;
    }
    std::reverse(plan.begin(), plan.end());
    if (plan.empty()) plan.push_back(std::vector<Op>(R, Op::make_wait()));
    return plan;
  };

  Node* root = make_node(initial_phys_config(ins), nullptr);
  explored.emplace(root->X, root);
  if (is_dd_goal(ins, root->X)) return extract_plan(root);

  Node* deepest = root;
  std::vector<Node*> open;  // DFS stack
  open.push_back(root);

  while (!open.empty() && !expired()) {
    Node* nd = open.back();
    if (is_dd_goal(ins, nd->X)) return extract_plan(nd);
    if (nd->tree_open.empty()) {
      open.pop_back();
      continue;
    }
    Constraint* c = nd->tree_open.front();
    nd->tree_open.pop_front();
    if (stats) stats->hl_expanded++;

    // low-level lazy expansion (design 5.1)
    if (c->depth < (int)R) {
      const int r = nd->order[c->depth];
      for (const Op& op : legal_local_ops(ins, nd->X, r, scratch, nd)) {
        c->kids.push_back(std::make_unique<Constraint>());
        Constraint* k = c->kids.back().get();
        k->parent = c;
        k->depth = c->depth + 1;
        k->who = r;
        k->what = op;
        nd->tree_open.push_back(k);
      }
    }
    // keep node on stack while its tree is non-empty
    auto res = carrier_pibt(ins, *nd, c, target_goal_dist, lower_dist, rng,
                            scratch, stats);
    if (!res.has_value()) continue;
    auto& [X_new, ops] = *res;

    auto it = explored.find(X_new);
    if (it != explored.end()) {
      if (stats) stats->duplicate_configs++;
      // LaCAM revisit semantics + M1 livelock signal (design 5.5): on heavy
      // revisiting, re-match rho with the node's current pairs tabooed and
      // reshuffle the intra-class order.  Ordering only — completeness kept.
      Node* ex = it->second;
      ex->revisits++;
      if (ex->revisits % 8 == 0) {
        std::vector<std::pair<int, int>> taboo;
        for (size_t i = 0; i < R; ++i)
          if (ex->guide.rho[i] >= 0)
            taboo.emplace_back((int)i, ex->guide.free_goal[i]);
        ex->guide = build_guidance(ins, ex->X, target_goal_dist, lower_dist,
                                   path_cache, scratch, ex, &taboo);
        ex->order = make_order(ins, ex->X, ex->guide, target_goal_dist);
        std::shuffle(ex->order.begin(), ex->order.end(), rng);
        std::stable_sort(ex->order.begin(), ex->order.end(), [&](int a, int b) {
          auto cls = [&](int i) {
            if (ex->X.kappa[i] >= 0) return 0;
            if (ex->X.kappa[i] == KAPPA_ANON) return 1;
            if (ex->guide.rho[i] >= 0) return 2;
            return 3;
          };
          return cls(a) < cls(b);
        });
      }
      if (!ex->tree_open.empty() && (open.empty() || open.back() != ex))
        open.push_back(ex);
      continue;
    }
    Node* child = make_node(std::move(X_new), nd);
    explored.emplace(child->X, child);
    parent_edge[child] = {nd, ops};
    if (child->depth > deepest->depth) deepest = child;
    if (is_dd_goal(ins, child->X)) return extract_plan(child);
    open.push_back(child);
  }
  if (stats) stats->timed_out = true;
  if (best_effort) *best_effort = extract_plan(deepest);
  return {};
}
