/*
 * Event-driven lifelong TAPF simulation loop.
 */
#pragma once

#include "lifelong_planning.hpp"
#include "tapf_planner.hpp"

struct LifelongSimulationConfig {
  std::string map_filename;
  std::string cache_filename;
  int num_agents = 1;
  int horizon = 1000;
  int seed = 0;
  std::vector<int> start_indexes;
  double planner_time_limit_sec = 2.0;
  bool planner_anytime = false;
  bool planner_force_full_assignment = false;
  int multi_carry_capacity = 1;
  int service_commit_agents = 0;
  int pickup_service_duration = 1;
  int delivery_service_duration = 1;
  int max_shared_drop_goal_agents = 5;
  int assignment_cost_mode = LIFELONG_ASSIGNMENT_COST_BASELINE;
  LifelongTaskGeneratorConfig task_config;
  bool debug = false;
};

struct LifelongTaskVisualizationRecord {
  int task_id = -1;
  LifelongTaskType task_type = LifelongTaskType::OUTBOUND;
  int start_index = -1;
  std::vector<int> goal_indexes;
  int release_timestep = -1;
  int pickup_timestep = -1;
  int completion_timestep = -1;
};

struct LifelongPlannerTraceRecord {
  int timestep = -1;
  bool should_replan = false;
  bool event_happened = false;
  bool plan_finished = false;
  bool previous_planner_failed = false;
  bool idle_unloaded_with_pending = false;
  bool snapshot_feasible = false;
  bool instance_valid = false;
  bool solution_found = false;
  bool timed_out = false;
  double planning_runtime_ms = 0;
  double assignment_time_ms = 0;
  double planner_search_time_ms = 0;
  int loaded_agents = 0;
  int assigned_unloaded_agents = 0;
  int idle_agents = 0;
  int pending_tasks = 0;
  int assigned_tasks = 0;
  int picked_tasks = 0;
  int completed_tasks = 0;
  int singleton_agents = 0;
  int multi_goal_agents = 0;
  int unique_target_count = 0;
  int total_goal_options = 0;
  int max_goal_options_per_agent = 0;
  int max_agents_per_target = 0;
  int duplicate_target_slots = 0;
  int agents_carrying_two_tasks = 0;
  int loaded_agents_with_pickup_options = 0;
  int loaded_agents_with_delivery_options = 0;
  int loaded_agents_with_both_pickup_delivery_options = 0;
  int loaded_pickup_goal_options = 0;
  int loaded_delivery_goal_options = 0;
  int loaded_wait_goal_options = 0;
  int max_loaded_pickup_options_per_agent = 0;
  int max_loaded_delivery_options_per_agent = 0;
  int root_loaded_pickup_assignments = 0;
  int root_loaded_delivery_assignments = 0;
  int root_loaded_wait_assignments = 0;
  int root_unloaded_pickup_assignments = 0;
  int root_unloaded_wait_assignments = 0;
  int root_initial_assignment_cost = 0;
  int final_loaded_pickup_assignments = 0;
  int final_loaded_delivery_assignments = 0;
  int final_loaded_wait_assignments = 0;
  int final_unloaded_pickup_assignments = 0;
  int final_unloaded_wait_assignments = 0;
  int max_loaded_distance_agent_pickup_options = 0;
  int max_loaded_distance_agent_delivery_options = 0;
  int max_loaded_distance_agent_wait_options = 0;
  int max_loaded_distance_agent_id = -1;
  int max_loaded_distance_agent_current_index = -1;
  int max_loaded_distance_agent_carried_tasks = 0;
  int max_loaded_distance_agent_root_target_index = -1;
  int max_loaded_distance_agent_final_target_index = -1;
  int max_loaded_distance_agent_root_target_type = 0;
  int max_loaded_distance_agent_final_target_type = 0;
  double average_target_region_agent_count = 0;
  int max_target_region_agent_count = 0;
  double average_target_region_loaded_agent_count = 0;
  int max_target_region_loaded_agent_count = 0;
  double average_target_region_loaded_waiting_count = 0;
  int max_target_region_loaded_waiting_count = 0;
  double average_target_region_loaded_stopped_count = 0;
  int max_target_region_loaded_stopped_count = 0;
  double average_carried_tasks_now = 0;
  int max_carried_tasks_now = 0;
  double average_loaded_distance_now = 0;
  int max_loaded_distance_now = 0;
  double average_priority_offset_now = 0;
  double max_priority_offset_now = 0;
  int max_priority_offset_agent_id = -1;
  int hl_loop_iterations = 0;
  int hl_nodes_created = 0;
  int hl_nodes_explored = 0;
  int hl_reinsertions = 0;
  int hl_duplicate_configs = 0;
  int open_max_size = 0;
  int constraints_popped = 0;
  int constraints_generated = 0;
  int constraint_failures = 0;
  int pibt_calls = 0;
  int pibt_failures = 0;
  int pibt_recursions = 0;
  int assignment_calls = 0;
  int assignment_changes = 0;
  int assignment_infeasible_count = 0;
  int service_child_validation_failures = 0;
  int service_child_stack_validation_failures = 0;
  int service_child_swap_validation_failures = 0;
  int final_assignment_changes = 0;
  int final_agent_assignment_changes = 0;
  long assignment_row_cache_requests = 0;
  long assignment_row_cache_hits = 0;
  int solution_depth = 0;
  unsigned solution_cost = 0;
  unsigned solution_h = 0;
  int service_satisfied_agents = 0;
  int service_satisfied_pickups = 0;
  int service_satisfied_deliveries = 0;
  int service_best_satisfied_agents = 0;
};

struct LifelongSimulationMetrics {
  std::string map_name;
  int num_agents = 0;
  int horizon = 0;
  int seed = 0;
  int generated_tasks = 0;
  int completed_tasks = 0;
  double throughput = 0;
  int alternating_completed_tasks = 0;
  double alternating_throughput = 0;
  int final_pending_tasks = 0;
  int final_assigned_tasks = 0;
  int final_picked_tasks = 0;
  double average_task_completion_time = 0;
  double average_pickup_time = 0;
  double average_delivery_time = 0;
  int planner_invocations = 0;
  int planner_success_count = 0;
  int planner_timeout_count = 0;
  int planner_failure_count = 0;
  int planner_snapshot_infeasible_count = 0;
  int planner_invalid_instance_count = 0;
  int planner_empty_solution_count = 0;
  int first_empty_loaded_agents = -1;
  int first_empty_assigned_unloaded_agents = -1;
  int first_empty_idle_agents = -1;
  int first_empty_unique_target_count = -1;
  int first_empty_singleton_agents = -1;
  int first_empty_multi_goal_agents = -1;
  double average_planner_runtime = 0;
  double max_planner_runtime = 0;
  double total_planner_runtime = 0;
  double total_assignment_runtime = 0;
  double total_planner_search_runtime = 0;
  double total_simulation_runtime = 0;
  double average_agent_idle_time = 0;
  double average_agent_loaded_time = 0;
  double average_agent_unloaded_time = 0;
  bool planner_force_full_assignment = false;
  double average_carried_tasks = 0;
  int max_carried_tasks = 0;
  double average_loaded_distance_since_last_delivery = 0;
  int max_loaded_distance_since_last_delivery = 0;
  int pickup_while_loaded_count = 0;
  int delivery_events = 0;
  double average_tasks_carried_at_delivery = 0;
  int multi_carry_capacity = 1;
  int max_shared_drop_goal_agents = 5;
  int assignment_cost_mode = LIFELONG_ASSIGNMENT_COST_BASELINE;
  long assignment_row_cache_requests = 0;
  long assignment_row_cache_hits = 0;
  double assignment_row_cache_hit_rate = 0;
  int map_width = 0;
  int map_height = 0;
  std::vector<std::vector<int> > executed_path_indexes;
  std::vector<std::vector<int> > agent_task_ids_by_timestep;
  std::vector<std::vector<int> > agent_task_phases_by_timestep;
  std::vector<std::vector<std::vector<int> > >
      agent_carried_task_ids_by_timestep;
  std::vector<std::vector<int> > agent_assigned_task_ids_by_timestep;
  std::vector<LifelongTaskVisualizationRecord> task_records;
  std::vector<LifelongPlannerTraceRecord> planner_trace_records;
  bool valid = true;
  std::string error;
};

LifelongSimulationMetrics run_lifelong_simulation(
    const LifelongSimulationConfig& config);
