import csv,json,html
from pathlib import Path
p=Path('/home/yimin/research/lacam/build/results/paper_2609_14208_repository/cache_bug_review')
t=json.loads((p/'trace_summary.json').read_text()); rr=list(csv.DictReader((p/'fixed_replays/rows.csv').open())); lookup={r['case_id']:r for r in rr}
records=[]
for old in t['records']:
 new=lookup[old['case_id']]
 records.append({'case_id':old['case_id'],'suite':old['suite'],'confirmed_false_unreachable':old['false_unreachable_queries'],'fixed_solved':new['solved'],'original_wall_time_s':old['original_wall_time_s'],'fixed_soc':new['soc']})
with (p/'case_review.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=list(records[0]));w.writeheader();w.writerows(records)
rows=''.join('<tr><td>'+html.escape(r['case_id'])+'</td><td>'+r['suite']+'</td><td>'+str(r['confirmed_false_unreachable'])+'</td><td>'+('成功' if r['fixed_solved']=='1' else '失败')+'</td><td><a href="original_trace/'+r['case_id']+'/stderr.log">原版追踪</a> · <a href="fixed_replays/artifacts/'+r['case_id']+'/ir/result.json">修复结果</a></td></tr>' for r in records)
page='''<!doctype html><meta charset="utf-8"><title>旧全量 IR 缓存问题核查</title><style>body{font:16px system-ui;background:#f5f7fa;color:#183047;max-width:1300px;margin:35px auto;padding:20px}section{background:white;padding:24px;margin:18px 0;border-radius:12px}p{line-height:1.8}td,th{text-align:left;padding:10px;border-bottom:1px solid #ddd}table{border-collapse:collapse;width:100%}a{color:#1263ba}.flow{font-size:20px;padding:20px;background:#fff1d5}input{padding:12px;width:90%}</style><h1>之前的全量 IR 实验也包含缓存问题</h1><p><a href="../comparison.html">返回论文对比</a> · <a href="case_review.csv">418 个测例 CSV</a> · <a href="trace_summary.json">真实追踪汇总</a> · <a href="archive_audit.json">修复成功轨迹复核</a></p><section><p>旧全量实验与新扩展实验使用同一个原版 IR 二进制。原版 SHA256：<code>ea05f2b7869b82a21c98e72a844513880d21395b7a79d6d1b5fc46b23230cd1b5fc46b23230cd1b</code></p><div class="flow">查询距离 → 找到当前目标节点 → 提前返回，未展开邻居 → 下一次查询缺少搜索前沿 → 错报不可达 → 目标分配失败</div><p><a href="../group_extension/ir_diagnosis/cache_replay.html">交互查看三节点最小复现与实际测例</a></p><table><tr><th>旧实验</th><th>旧 IR 失败</th><th>追踪确认错误不可达</th><th>修复后成功</th><th>修复后仍失败</th></tr><tr><td>Group</td><td>160</td><td>160</td><td>160</td><td>0</td></tr><tr><td>Common</td><td>258</td><td>21</td><td>13</td><td>245</td></tr></table><p>418 个旧失败均在初始目标分配或分配优化阶段退出，尚未进入初始 MAPF 路径搜索。Common 的 21 个缓存错误中，13 个恢复成功、8 个仍失败。其余 237 个没有记录到错误不可达，原版贪心分配耗尽可选目标，修复后仍失败。贪心分配失败不代表实例无解。</p></section><section><h2>旧统计怎么理解</h2><p>旧成功率和曲线描述的是含缓存缺陷的原版 IR。旧成功路径已通过合法性验证；本次发现不使这些路径自动失效。但是缓存会影响目标选择，因此成功率、SOC 和时间的算法比较需要用修复版全量重跑后再评估。</p><p>此次用 56 路并行，只重跑了 418 个旧失败，预算仍为每例 10 秒。新成功 173 个均另行核查归档轨迹。原来成功的 9,342 个尚未用修复版重跑。不能把这 173 个直接补进旧统计并称为“修复版全量成功率”；修复后目标选择变化也可能使某些原成功案例失败。</p></section><section><h2>逐测例核查与日志</h2><input placeholder="输入地图或测例名筛选" oninput="document.querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.textContent.includes(this.value))"><table><thead><tr><th>测例</th><th>实验</th><th>错误不可达次数</th><th>修复结果</th><th>原始证据</th></tr></thead><tbody>'''+rows+'</tbody></table></section>'
page=page.replace('ea05f2b7869b82a21c98e72a844513880d21395b7a79d6d1b5fc46b23230cd1b5fc46b23230cd1b','ea05f2b7869b82a21c98e72a844513880d21395b7a79d6d1b5fc46b23230cd1b')
if (p.parent.parent/'paper_2609_14208_cache_comparison/completion_audit.json').exists():
 page=page.replace('<h1>之前的全量 IR 实验也包含缓存问题</h1>', '<h1>之前的全量 IR 实验也包含缓存问题</h1><section><strong>本页保留全量重跑之前的 418 个失败核查。</strong><p>随后已完成全部 9,760 个实例的修复版重跑。<a href="../full_ir_cache_fixed/comparison.html">查看最新全量统计与图</a></p></section>')
(p/'index.html').write_text(page)
